### ISSUE TITLE
开发路线图 | Development Roadmap

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/StarRailCopilot#10]
## 框架相关
1. 【已完成 LmeSzinc 】Alas框架迁移
2.  接入调度器
3.  移除 uiautomator2 相关的截图及控制方法，移除 atx-agent （待讨论）
4.  适配全模拟器启停
5.  作为插件接入 Alas 本体 （待讨论）
6.  废除 git pull 式更新，新的版本分发方案 （待讨论）

## 体力相关

1. 【开发中 LmeSzinc 】副本 UI 切换，战斗处理
2. 计算体力并调度任务
3. 面向养成需求的体力规划，输入养成目标自动安排打本直到达成目标 （待讨论）

## 每日相关

1. 【已完成 5upernova-heng 】领取每日奖励及每日识别
2. 【已完成 5upernova-heng 】拍照
3. 【已完成 Driver-C 】合成消耗品
4. 【开发中 Driver-C 】使用消耗品
5. 完成每日任务并领取奖励
6. 【开发中 Zebartin 】委派系统
7. 领取大月卡奖励
8. 使用助战，使用支援角色并获得战斗胜利1次 （待讨论）
9. 打深渊一，完成1次「忘却之庭」
10. 打模拟宇宙一，通关「模拟宇宙」（任意世界）的1个区域
11. 跑腿任务，完成1个日常任务 （待讨论）

## 地图相关

1. 解包地图及点位信息整理
2. 地图界面识别及传送
3. 小地图识别（lme
4. 多图层的寻路模块（lme
5. 地图移动至屏幕操作的转换（lme
6. 【开发中 Yuanyuanyuan2020 】编队
7. 锄地线路整理
8. 锄地模块
9. 模拟宇宙玩法梳理
10. 模拟宇宙模块

**Comment by Lzsh1** [comment]
大佬加油

**Comment by yysyinan** [comment]
冲冲冲

**Comment by yysyinan** [comment]
需要我们做什么？

**Comment by LmeSzinc** [comment]
选择你感兴趣的任务开始做就可以了。

参考 Alas 的开发文档 https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/1.-Start ，目录在侧边栏。一些新东西像是 paddleocr 和 Keywords 类就要看代码了。

![image](https://github.com/LmeSzinc/StarRailCopilot/assets/37934724/e1e520f4-471e-4b04-b305-01f48a5562d0)

**Comment by foodtooth** [comment]
我看项目没有开discussion，在这写写地图相关的抛砖引玉一下：

> 地图相关.7的锄地线路：

单纯的线路已有很多up整理过了，纯打怪版，或者带破坏物版，都有；
应该只需要人力转化一次坐标

**注！** 可以考虑线路跳过仙舟的金人……

> 地图相关.9的模拟宇宙玩法：

* 基本思路可以是，手动配队；配置队伍编号和可以打的模拟宇宙编号
* 要求练度自然是可以auto打过第一个精英
* 脚本不用考虑流派的花样，都是求稳为主，应该是宇宙4丰饶，其它都是存护
* 祝福选不到对应流派时候选项也有一定的相性，但是我觉得初版可以不用考虑，留个接口就好

以上。:)

**Comment by LmeSzinc** [comment]
目前还在观望

> 吕明珠LmeSzinc在轻轨 2023/7/5 12:48:32
唉这个是一个很有意思的事情，隔壁方舟是一个以刷材料为养成核心的游戏，也有这样的刷材料规划网站，但是maa到现在都还没有规划刷材料的功能

> 吕明珠LmeSzinc在轻轨 2023/7/5 12:50:03
也偶尔会有人提这个，但是开发都没什么兴趣的样子，是为什么呢（

> 吕明珠LmeSzinc在轻轨 2023/7/5 12:50:13
我觉得这个事情很有可能也发生在铁轨上

> 吕明珠LmeSzinc在轻轨 2023/7/5 12:51:59
我的分析就是，方舟的材料主要来源其实不是去规划刷图，而是在活动图里面掉落，活动图的掉率比常规图高很多

> 吕明珠LmeSzinc在轻轨 2023/7/5 12:52:35
那只要你活动，保证一段时间的全勤，那么你的材料就不会缺，会需要用到这样的规划，刷图功能的只有新入坑的玩家，因为没有经历那么多活动

> 吕明珠LmeSzinc在轻轨 2023/7/5 12:53:08
开发都是老玩家为主了那对这些功能就是兴趣不大

**Comment by walksQAQ** [comment]
想问一下 以后能把alas和maa当插件丢src里不（）（）（） 感觉src的界面好像比alas好点
