### ISSUE TITLE
請問截圖與操作方式

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/StarRailCopilot#100]
SRC目前是限MaaTouch/scrcpy
是adb_nc不適合嗎，因為我記得alas有的

**Comment by LmeSzinc** [comment]
scrcpy 最快，消耗也最低，但是传输的是有损视频流。

也不能说最快吧，只是帧率可调，现在设置的是 10fps，根据采样定理相当于 Alas 里的截图间隔 200ms
