### ISSUE TITLE
BUG: 一直执行姬子试用即使相关任务已被完成

### ISSUE THREAD

**Issue by WLLEGit** [LmeSzinc/StarRailCopilot#106]
起来发现src卡在了错误处理，原因似乎是执行次数过多。手动启动了一次，一直在循环查看每日任务-进入姬子使用，但是此时和试用相关的”完成5次弱点击破”已经被领取了

> 2023-09-25 04:37:55.447 | INFO | [OCR_DAILY_QUEST 0.237s] ['完成1个日常任务', '完成1次「凝滞虚影」',                   
'将任意遗器等级提升1次', '通关「模拟宇宙」（任意世界）的1个区域', '前往', '前往', '前往', '前往']     
> 2023-09-25 04:37:56.295 | INFO | [OCR_DAILY_QUEST 0.253s] ['将任意遗器等级提升1次',                                    
'通关「模拟宇宙」（任意世界）的1个区域', '派遣1次委托', '累计触发弱点击破效果5次', '前往', '前往', '已领取', '已领取'] 
![2023-09-25_12-19-18-053647](https://github.com/LmeSzinc/StarRailCopilot/assets/71222785/62fb285d-ab94-4dbe-b53b-c6ddaa51dd17)
![2023-09-25_12-19-26-751678](https://github.com/LmeSzinc/StarRailCopilot/assets/71222785/39720f8d-cf2d-486c-872c-82f4a1bcfe32)

[2023-09-24_alas.txt](https://github.com/LmeSzinc/StarRailCopilot/files/12710393/2023-09-24_alas.txt)
[2023-09-25_alas.txt](https://github.com/LmeSzinc/StarRailCopilot/files/12710394/2023-09-25_alas.txt)

**Comment by LmeSzinc** [comment]
更新 SRC ， 2591bb3a284e432a74e7fb5df7258af86dc75df4

**Comment by WLLEGit** [comment]
似乎是我把deploy.yaml中的global改成cn导致的问题，改回去就正常更新了
