### ISSUE TITLE
设置自动启用软件src和模拟器

### ISSUE THREAD

**Issue by jionglianmao** [LmeSzinc/StarRailCopilot#118]
能考虑添加个设置时间自动启动src跟模拟器（src内部启动模拟器）的功能吗
`隔壁MAA有这功能很舒服，打完直接自动关机电脑

**Comment by LmeSzinc** [comment]
config/deploy.yaml 里可以设置启动后运行某个配置文件，配置文件的调度器启动之后会自动开模拟器

https://github.com/LmeSzinc/StarRailCopilot/blob/271bdc9e1c52115a832ad92aeacf9504aaf34d8f/config/deploy.template.yaml#L156-L160

> 在设置正确的情况下，SRC 可以自动启动模拟器和游戏，你不需要手动开启模拟器和游戏。模拟器启动目前只支持 MuMu 系和夜神系模拟器。

**Comment by jionglianmao** [comment]
可能是我表述的不清楚
我是说src里面没有自己设置时间定时启动src.exe 这个板块 （希望能加一个任务完成后自动关机等） 
进入软件后，还需要自己开启调度器（缺少进入自动开启选项板块，会方便挂机些）
还有src这个软件在运行完毕后，只能关闭模拟器内的游戏，不能关闭模拟器
最重要的还是src的调度器启动后，游戏运行完毕src的调度器会一直运行

如果可以解决的话，src可以算得上真正的全自动托管

**Comment by LmeSzinc** [comment]
保持调度器运行就可以了，调度器会安排接下来什么时间运行什么任务，不需要自己设定

**Comment by jionglianmao** [comment]
那能加一个启用src时自动开启调度器，以及自己设置电脑定时启动src（如图）
![屏幕截图 2023-09-30 235153](https://github.com/LmeSzinc/StarRailCopilot/assets/140719899/53c7c63e-4473-4a19-9310-ed4cf656f62c)
