### ISSUE TITLE
在双倍花活动时仍刷仪器副本，双倍活动识别失败

### ISSUE THREAD

**Issue by Yinhaoran1128** [LmeSzinc/StarRailCopilot#127]
我设置了在双倍花活动时刷材料本，今天开始双倍活动，但脚本仍然在刷仪器本

**Comment by Yinhaoran1128** [comment]
大佬您好，我更新后仍然无法正确识别双倍活动

**Comment by Zebartin** [comment]
>大佬您好，我更新后仍然无法正确识别双倍活动
观察日志并没有判断是否双倍的过程
https://github.com/LmeSzinc/StarRailCopilot/pull/128#issuecomment-1742598827

这个是否有双倍的判断每天只会检查一次，因为今天已经检查过了，所以在明天4点之前不会再检查
我这边的建议是可以手动把配置文件里的`DungeonDouble`对应的时间改成昨天。果不知道怎么改我也不好说了，让lme解决吧 |ू･ω･` )

https://github.com/LmeSzinc/StarRailCopilot/blob/bbe31fdf4393f63e05af1088b59be569af19af24/config/template.json#L61

```diff
      "DungeonDouble": {
-       "time": "2023-10-02 12:34:10",
+       "time": "2023-10-01 12:34:10",
        "calyx": 8,
        "relic": 0
      },
```

**Comment by Yinhaoran1128** [comment]
好的好的谢谢大佬！明白了~

**Comment by Yinhaoran1128** [comment]
出现了另一个问题，每次进行每日副本任务时，他只会读取当天四点记录的双倍次数
假如第一次清体力，拥有超过120点体力，次数上限为12，那么它会打12次后开始打预设的其他副本
但当天第二次清体力的时候，它又会读取12次的上限，再打12次后才打别的副本
是否可以修改成每次清体力都检查一下每日双倍的次数

**Comment by Yinhaoran1128** [comment]
新鲜的bug，在双倍次数剩余次数为两位数时，ocr结果：1012、1112、1212，而根据匹配规则，1012和1212无法识别，1112会被识别为1/12，一位数则没有问题，例如剩余9次，ocr结果9112，识别为9/12
如果仅修改规则，1/12和11/12将无法区分
