### ISSUE TITLE
新号副本没开全会出现无限重启游戏的情况

### ISSUE THREAD

**Issue by S07453881** [LmeSzinc/StarRailCopilot#131]
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/99027027/c75ecfcd-bf82-424c-a34f-e8a79202cc0a)

**Comment by S07453881** [comment]
![2023-10-03_20-49-02-869237](https://github.com/LmeSzinc/StarRailCopilot/assets/99027027/e12c4f49-e1d2-40c4-b8a2-a1c99893d5d0)

**Comment by S07453881** [comment]
手动切换到金花的界面就可以正常运行了，肯能是模拟宇宙的问题？

**Comment by LmeSzinc** [comment]
需要自己解锁游戏系统才能开始运行脚本

**Comment by S07453881** [comment]
> 需要自己解锁游戏系统才能开始运行脚本
解锁游戏系统是指？把所以副本全开了再用？
