### ISSUE TITLE
频发AdbError

### ISSUE THREAD

**Issue by WLLEGit** [LmeSzinc/StarRailCopilot#133]
不知道是不是和MAA一起用的原因，MAA那边把adb路径设置为了src adbutils binary的adb，并且src设置了ReplaceAdb=False。
MAA似乎运行得挺正常，src这里每一两天就会出现AdbError，凌晨出错，早上观察到模拟器和adb都是运行着的状态，手动重启调度器就又正常了。尝试过手动复现一直没成功。

Win11, Mumu12模拟器, MAA和崩铁是两个多开
报错详情见2023-10-03_gui.txt末尾

[2023-10-03_gui.txt](https://github.com/LmeSzinc/StarRailCopilot/files/12798683/2023-10-03_gui.txt)
[alas.json.txt](https://github.com/LmeSzinc/StarRailCopilot/files/12798686/alas.json.txt)
[deploy.yaml.txt](https://github.com/LmeSzinc/StarRailCopilot/files/12798688/deploy.yaml.txt)

10.5二更：又出现了AdbError，具体行为是昨晚9点src运行正常，今早4点src报错，6点MAA运行正常（但是出现了“模拟器断开，正在尝试重连”的字样），9点手动重启调度器后卡在开始的列车界面，关闭重启后运行正常

**Comment by LmeSzinc** [comment]
上传 log 文件，但不是 gui 或者 webapp 的 log 文件

**Comment by WLLEGit** [comment]
整个log目录
[log.zip](https://github.com/LmeSzinc/StarRailCopilot/files/12819025/log.zip)
之前有几个跟这个bug无关的error子目录被我清了下
