### ISSUE TITLE
添加强制重置按钮

### ISSUE THREAD

**Issue by BeatSeat** [LmeSzinc/StarRailCopilot#158]
### 你的功能请求是否与问题有关？

目前SRC有一些错误页面处理尚未做好，例如#134中因玩家手动登录挤占游戏时无法通过错误处理解决。另外例如未来得及更新SRC导致出现部分问题时也会卡在相应页面，即使在SRC端停止也无济于事。我个人将SRC部署在远程主机上，不能通过网页端直接解决限制很大。

### 解决方案

希望添加一个强制重置按钮，用作错误处理未能按期望运行时的解决方法，主要用途为关闭游戏、关闭模拟器等等。

**Comment by LmeSzinc** [comment]
有错误请上报

**Comment by wendavid552** [comment]
典型错误例如Issue #134 ，因挤占登录造成的登录问题直接重启游戏再度登录可能并不合适。
