### ISSUE TITLE
windows睡眠后SRC主界面白屏

### ISSUE THREAD

**Issue by Asxcvbn** [LmeSzinc/StarRailCopilot#159]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

平时是正常使用， 但是如果在SRC没有最小化到托盘的情况下，比如窗体在其他窗口的后面但是未最小化，此时进入windows睡眠，会正常进入睡眠模式。唤醒后，查看SRC, 可以看到SRC主窗体白屏。此时假如睡眠之前没有退出调度任务，那么可能会正常进入任务（模拟器正常自动操作）

假如在睡眠之前最小化到托盘（右上角向下的箭头）， 那么睡眠唤醒之后一切正常。

白屏后，最小化到托盘并重新打开SRC不会改善。

同时，因为应该只是显示问题，没有错误log

下面的截图栏为主窗体白屏时的SRC窗体。

### 如何复现

在SRC没有最小化到托盘的情况下，比如窗体在其他窗口的后面但是未最小化，此时进入windows睡眠，会正常进入睡眠模式。唤醒后，查看SRC, 可以看到SRC主窗体白屏。

### 预期行为

自然的，不应当白屏。

### 截图

![图片](https://github.com/LmeSzinc/StarRailCopilot/assets/63904802/4a38c564-31ce-414c-8ba0-515fa11ac9a4)

### 还有别的吗？

win10 22H2 19045.3155 的确不是最新版系统，但是应该和这个问题关系不大。

**Comment by LmeSzinc** [comment]
尝试 CTRL+R 刷新

**Comment by Asxcvbn** [comment]
似乎可以！感谢
