### ISSUE TITLE
src关闭后mumu后台残留问题

### ISSUE THREAD

**Issue by TomIsFat** [LmeSzinc/StarRailCopilot#173]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

每日运行完成后，SRC实例和mumu12模拟器均在可见的前台窗口

这时候直接关掉SRC，SRC和mumu12的窗口均消失不见

但是mumu仍然会留下不可见的后台，一直占用系统资源

![image](https://github.com/LmeSzinc/StarRailCopilot/assets/76768214/09df291d-2326-497b-83af-9d4633d5b039)

### 如何复现

1. 确定SRC设置-优化设置-当任务队列清空时：关闭游戏
2. 运行SRC实例（正常完成每日任务，SRC实例仍然在运行，mumu12窗口也存在）
3. 右上角直接关闭SRC（确定要关闭SRC吗？所有实例都将停止：选择确定；src，mumu窗口均消失）
4. 出现问题：mumu有后台残留

### 预期行为

mumu后台应该无残留

**Comment by LmeSzinc** [comment]
SRC 不会关闭也不应该关闭模拟器

**Comment by TomIsFat** [comment]
bug描述：当关闭src的时候，MuMu模拟器界面被意外关闭


期望的行为：当关闭src时，MuMu模拟器界面不被关闭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月27日(周五) 上午7:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LmeSzinc/StarRailCopilot] src关闭后mumu后台残留问题 (Issue #173)




 
SRC 不会关闭也不应该关闭模拟器

**Comment by gongfuture** [comment]
遇到同样情况，此前使用代码直接运行没遇到过，换了一键端遇到好些次了

**Comment by gongfuture** [comment]
> 遇到同样情况，此前使用代码直接运行没遇到过，换了一键端遇到好些次了

附图
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/60888755/0a34bacc-9dfc-43f3-b321-674171cd761b)

**Comment by gongfuture** [comment]
> > 遇到同样情况，此前使用代码直接运行没遇到过，换了一键端遇到好些次了
> 
> 附图 ![image](https://private-user-images.githubusercontent.com/60888755/301716985-0a34bacc-9dfc-43f3-b321-674171cd761b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDQ0NjUsIm5iZiI6MTcwNjg0NDE2NSwicGF0aCI6Ii82MDg4ODc1NS8zMDE3MTY5ODUtMGEzNGJhY2MtOWRmYy00M2YzLWIzMjEtNjc0MTcxY2Q3NjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAzMjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZjZmYTJkNWMyOTdjMDViZjEwYmZjOTk4NTg4NmJiMmY4M2ZmYWVhOTE0ODgxZmM5NTQ5MmUzMDIyYTI2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F92ksnf9nfCwbXW6yI458ciivM4doSPqb0f2hHnitAk)

最后关闭时webapp有报错
[2024-02-02_webapp.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14133805/2024-02-02_webapp.txt)

**Comment by gongfuture** [comment]
期望修复这个bug，近期几乎每次都能复现

**Comment by TomIsFat** [comment]
> 期望修复这个bug，近期几乎每次都能复现

根据我最近的经验，建议养成不要直接右上角的叉关闭SRC的习惯，否则就会有后台一直占用的问题。

想要正常关闭，可以尝试以下的方法：
方法一：点击主界面的停止后，再右上角关闭SRC
方法二：先关闭模拟器，再关闭SRC

**Comment by gongfuture** [comment]
> > 期望修复这个bug，近期几乎每次都能复现
> 
> 根据我最近的经验，建议养成不要直接右上角的叉关闭SRC的习惯，否则就会有后台一直占用的问题。
> 
> 想要正常关闭，可以尝试以下的方法： 方法一：点击主界面的停止后，再右上角关闭SRC 方法二：先关闭模拟器，再关闭SRC

我确实知道避免的方法，可是这终究是个不小的bug，感觉最近都没有人跟踪这个issue，所以想再提一下

**Comment by TomIsFat** [comment]
> > > 期望修复这个bug，近期几乎每次都能复现
> > 
> > 
> > 根据我最近的经验，建议养成不要直接右上角的叉关闭SRC的习惯，否则就会有后台一直占用的问题。
> > 想要正常关闭，可以尝试以下的方法： 方法一：点击主界面的停止后，再右上角关闭SRC 方法二：先关闭模拟器，再关闭SRC
> 
> 我确实知道避免的方法，可是这终究是个不小的bug，感觉最近都没有人跟踪这个issue，所以想再提一下

@LmeSzinc 说SRC不会关闭也不应该关闭模拟器
那么我猜测问题应该出在SRC进程启动了mumu模拟器进程，由于SRC进程意外被关闭导致mumu这个进程也被关闭了。

**Comment by TomIsFat** [comment]
> > > 期望修复这个bug，近期几乎每次都能复现
> > 
> > 
> > 根据我最近的经验，建议养成不要直接右上角的叉关闭SRC的习惯，否则就会有后台一直占用的问题。
> > 想要正常关闭，可以尝试以下的方法： 方法一：点击主界面的停止后，再右上角关闭SRC 方法二：先关闭模拟器，再关闭SRC
> 
> 我确实知道避免的方法，可是这终究是个不小的bug，感觉最近都没有人跟踪这个issue，所以想再提一下

再艾特了一下作者，看看能不能解决吧

**Comment by TomIsFat** [comment]
已修复
