### ISSUE TITLE
异常报错：[WinError 10054] 远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by XYZliang** [LmeSzinc/StarRailCopilot#179]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

使用最新版本的MuMu模拟器12和SRC，均为全新下载。
5037端口未被占用，也未开启代理和杀毒软件。
重试模拟器、SRC、重启电脑均无效，依旧报错。
系统win11 dev 23570.1000
不使用任何安卓手机，因此电脑没有安装相关adb环境和安卓管家类软件
### 如何复现

点击调度器启动

### 相关 Logs

```Text
[WinError 10054] 远程主机强迫关闭了一个现有的连接。
```

### 截图

<img width="1659" alt="image" src="https://github.com/LmeSzinc/StarRailCopilot/assets/59312540/f3ff0517-f590-4619-afe7-37ce06cd2ffc">

**Comment by LmeSzinc** [comment]
上传完整log

**Comment by XYZliang** [comment]
抱歉，才发现有日志文件，相关文件附上
[log.zip](https://github.com/LmeSzinc/StarRailCopilot/files/13217460/log.zip)

**Comment by LmeSzinc** [comment]
1. 检查是否有雷电模拟器在后台运行，有就关掉
2. 尝试管理员执行 `netsh winsock reset` 然后重启电脑
3. 都不行就qq群里联系我

**Comment by XYZliang** [comment]
> 1. 检查是否有雷电模拟器在后台运行，有就关掉
> 2. 尝试管理员执行 `netsh winsock reset` 然后重启电脑
> 3. 都不行就qq群里联系我

感谢，尝试管理员执行 `netsh winsock reset` 还没重启电脑就正常了
