### ISSUE TITLE
请问是不是模拟宇宙还是不可以自动刷哇

### ISSUE THREAD

**Issue by MiloGame** [LmeSzinc/StarRailCopilot#19]
<img width="323" alt="image" src="https://github.com/LmeSzinc/StarRailCopilot/assets/125568740/cd450c85-7a9c-4204-9841-bcab10ea1042">

**Comment by Driver-C** [comment]
还没有这个功能

**Comment by wEuphorIA** [comment]
https://github.com/CHNZYX/Auto_Simulated_Universe 这个可以

**Comment by aaahai00** [comment]
现在行了

**Comment by LmeSzinc** [comment]
#223
