### ISSUE TITLE
强行启动每日任务

### ISSUE THREAD

**Issue by 1020623818** [LmeSzinc/StarRailCopilot#201]
### 你的功能请求是否与问题有关？

每次在运行前关掉每日任务后，点击启动，过一会每日任务就自动被勾上了
我拿这个给小号清理智，主线没怎么推，有时候每日任务要给我造那个合成我连配方都没有，就陷入不停重启的循环里了

### 解决方案

允许用户关闭每日任务，并允许用户指定每项每日任务是否执行

**Comment by LmeSzinc** [comment]
速溶茶默认所有游戏系统已经解锁，大部分脚本也是这么设计的。如果需要考虑这点会带来更高开发成本+更多测试场景，且收益很低，贡献者们和我都没有兴趣

**Comment by aaahai00** [comment]
> 速溶茶默认所有游戏系统已经解锁，大部分脚本也是这么设计的。如果需要考虑这点会带来更高开发成本+更多测试场景，且收益很低，贡献者们和我都没有兴趣

实际问题为每日任务关闭的选项失去了作用，在关闭的情况下仍然会执行
（实际表现为关闭那时每日任务确实从调度器移除了，但是后面又被别的地方引用导致重新被打开）
