### ISSUE TITLE
Scrcpy error: FileNotFoundError

### ISSUE THREAD

**Issue by seriaati** [LmeSzinc/StarRailCopilot#21]
[2023-06-19_alas.txt](https://github.com/LmeSzinc/StarRailCopilot/files/11789558/2023-06-19_alas.txt)

**Comment by LmeSzinc** [comment]
Make sure you have ADB in environment, or set it to `config/deploy.yaml` AdbExecutable

**Comment by seriaati** [comment]
oh, I see.
should probably include that in the readme.
