### ISSUE TITLE
自动账号切换

### ISSUE THREAD

**Issue by aaahai00** [LmeSzinc/StarRailCopilot#212]
### 你的功能请求是否与问题有关？

要清另一个账号的日常，每次都要手动切换账号挺麻烦的，并且切换账号后直接启用调度器会报错，还要手动进入游戏
详情：#214

### 解决方案

可以提前提交一些信息（手机号前三位后四位，或是由程序截图）给src使用文字或图像识别识别要切换的账号，以便更方便的完成小号的任务，至于怎么识别需要切换账号，应该可以用uid识别吧

### 其他内容
简短描述就是，在src启动并进入游戏出现uid时识别是否是所需账号，不是就自动切换为所需账号，并且在src多配置文件的调度器启用时按开启顺序处理

**Comment by Zebartin** [comment]
我是建议一个号对应一个模拟器实例、一个src配置

**Comment by aaahai00** [comment]
> 我是建议一个号对应一个模拟器实例、一个src配置

我也是这么想的，现在来说完全不冲突的方法是用不同的模拟器，但这样会占用大量的空间，单模拟器切换账号又有些麻烦
希望src能识别什么时候需要切换账号
首先要做到在同一个模拟器同时开启多个src配置不冲突(就是排序运行)
例如:同时开启ABC的src配置，src自动排序或手动指定优先级(如A-B-C)
实际运行希望效果:首先A配置完成所有待定任务→B配置激活，检测uid并不是b账号的，自动切换账号，B配置完成所有待定任务→C配置激活，检测账号并自动切换，后期就继续按顺序进行

**Comment by aaahai00** [comment]
> > 按照一贯的传统，不会添加任何与帐号切换有关的功能

可以理解，本来其实手动切换也不是不行，主要切换完还不能立马启用调度器，要么把游戏关了，要么就手动进入玩游戏才能开，不然一会就报错
