### ISSUE TITLE
SRC连接MUMU12模拟器报错

### ISSUE THREAD

**Issue by zishiluojin** [LmeSzinc/StarRailCopilot#218]
### 在提问之前...

- [x] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

电脑系统win11,模拟器是MUMU12(V3.6.11)，SRC启动时报错

### 截图

![SRC配置](https://github.com/LmeSzinc/StarRailCopilot/assets/45036965/98b8363e-d562-45d6-acb1-a9d879f3d58c)
![MUMU模拟器版本](https://github.com/LmeSzinc/StarRailCopilot/assets/45036965/750dd736-f876-44c3-9798-25a187c91dde)
[2023-12-11_src.txt](https://github.com/LmeSzinc/StarRailCopilot/files/13637583/2023-12-11_src.txt)

**Comment by Yinhaoran1128** [comment]
改回auto, 或者检查一下mumu有没有把端口改了, 有时候会莫名其妙+1或者-1

**Comment by zishiluojin** [comment]
> 改回auto, 或者检查一下mumu有没有把端口改了, 有时候会莫名其妙+1或者-1

尝试了auto还是无法正常连接，我尝试了scrcpy来连接127.0.0.1:16384端口，scrcpy可以正常连接
