### ISSUE TITLE
希望加入任务模块：储存沉浸器

### ISSUE THREAD

**Issue by Asxcvbn** [LmeSzinc/StarRailCopilot#219]
### 你的功能请求是否与问题有关？

由于目前暂时还没支持模拟宇宙的自动刷取，模拟宇宙周常：刷两把模拟宇宙目前需要手动进行。但是我可能愿意在这两把模拟宇宙中领取遗器，但是在等待SRC完成今天的自动操作后，一定是没剩多少体力的，因此无法领取。为此，

### 解决方案

只需要加入任务模块：储存沉浸器，在正常的调度中加入该模块同时设置储存沉浸器最大数目0-8/个，在执行任务时，重复储存沉浸器直到达到预定数目, 

基本上就可以保证在每周手动刷取模拟宇宙的时候，都有足够的沉浸器来领取遗器。

### 其他内容

![图片](https://github.com/LmeSzinc/StarRailCopilot/assets/63904802/cac1d8cd-8141-4086-9387-d5c262d1f9be)

**Comment by Yinhaoran1128** [comment]
模拟宇宙功能正在激情内测中, 近期应该就会推出了, 请耐心等待一下~

**Comment by LmeSzinc** [comment]
#223
