### ISSUE TITLE
运行src安装卡在15%

### ISSUE THREAD

**Issue by 0onin** [LmeSzinc/StarRailCopilot#230]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

可以正常访问github，开不开加速、管理员运行均卡在此处

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
==================== FETCH REPOSITORY BRANCH ====================
"D:/Tool/StarRailCopilot_0.5.3_fullcn/StarRailCopilot/toolkit/Git/mingw64/bin/git.exe" fetch origin master
[ failure ], error_code: 128
+-----------------------------------------------------+
|                    UPDATE FAILED                    |
+-----------------------------------------------------+
==================== SHOW DEPLOY CONFIG ====================
Repository: cn
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
Last command: "D:/Tool/StarRailCopilot_0.5.3_fullcn/StarRailCopilot/toolkit/Git/mingw64/bin/git.exe" fetch origin master
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe
Take the screenshot of entire window if you need help
fatal: unable to access 'https://github.com/LmeSzinc/StarRailCopilot/': Failed to connect to github.com port 443: Timed out
Error: fatal: unable to access 'https://github.com/LmeSzinc/StarRailCopilot/': Failed to connect to github.com port 443: Timed out
```

[2023-12-26_webapp.txt](https://github.com/LmeSzinc/StarRailCopilot/files/13770137/2023-12-26_webapp.txt)

### 截图

![Snipaste_2023-12-26_16-11-34](https://github.com/LmeSzinc/StarRailCopilot/assets/65103860/0551ba0a-9c7c-4629-b481-c6ede2fcf3ab)

**Comment by LmeSzinc** [comment]
发当天的 log/*_webapp.txt

**Comment by 0onin** [comment]
> 发当天的 log/*_webapp.txt

[2023-12-26_webapp.txt](https://github.com/LmeSzinc/StarRailCopilot/files/13770132/2023-12-26_webapp.txt)

**Comment by LmeSzinc** [comment]
重新下载一份看看
https://github.com/LmeSzinc/StarRailCopilot/releases

**Comment by n2don** [comment]
ran into similar problem, delete the .git and github folder and restart fixed it, from the logs it seems it was hanging on git update. 
"遇到了类似的问题，删除.git和github文件夹然后重启解决了这个问题，从日志来看似乎是在git更新时挂起的。这是由AI翻译的。"
