### ISSUE TITLE
模拟宇宙积分满了,就不能再打了,希望满了也可以再打

### ISSUE THREAD

**Issue by rosebudgrave** [LmeSzinc/StarRailCopilot#231]
### 你的功能请求是否与问题有关？

模拟宇宙积分满了不能在打了

### 解决方案

模拟宇宙积分满了也可以打,可以做一个勾选框,满了可以打

**Comment by aaahai00** [comment]
其实领取奖励的次数有上限的，直接改成设定次数就好一点

**Comment by ACNicotine** [comment]
认同，打模拟宇宙会掉很多材料，出一个这样的功能可以无限刷了，但是不知道这样一直挂模拟宇宙会不会被封

**Comment by aaahai00** [comment]
> 认同，打模拟宇宙会掉很多材料，出一个这样的功能可以无限刷了，但是不知道这样一直挂模拟宇宙会不会被封

这个项目用的是图片识别，理论来说没什么风险，怕就别用

**Comment by wpae0528** [comment]
同感，希望有设定次数的，之前用隔壁的挂pc端，一周挂两天，不过那个pc端的占着电脑，很麻烦

**Comment by WHU-ZhuLin** [comment]
只要把最下面的开发模式勾上就能一直刷，但是说明里好像有个遇错误即停止，虽然目前没触发过。

**Comment by aaahai00** [comment]
> 只要把最下面的开发模式勾上就能一直刷，但是有个遇错误即停止，目前比较容易触发。

那个错误停止应该是拿来反馈bug用的，方便测试，正常来说有错误就直接退出重进，每次你还没来得及停止就给你重置了不好抓记录的

**Comment by aaahai00** [comment]
> 只要把最下面的开发模式勾上就能一直刷，但是有个遇错误即停止，目前比较容易触发。

其实就算能一直打也最好把计数做出来，方便调整次数，也可以查看到底打了几次

**Comment by rosebudgrave** [comment]
> 只要把最下面的开发模式勾上就能一直刷，但是有个遇错误即停止，目前比较容易触发。

这样可以 满了也接着打,可以的.

**Comment by aaahai00** [comment]
> > 只要把最下面的开发模式勾上就能一直刷，但是有个遇错误即停止，目前比较容易触发。
> 
> 这样可以 满了也接着打,可以的.

但不建议，这选项的逻辑是，遇到错误才停止，但正常运行的情况下很容易卡墙之类的错误，正常它会自己排除错误（退出重进），拍了这个选项大概就不能自己排除了，很容易出错误，
有需要的可以试试这个项目（基于星铁pc端）https://github.com/CHNZYX/Auto_Simulated_Universe
