### ISSUE TITLE
希望加入直接控制PC端崩铁的功能

### ISSUE THREAD

**Issue by Luochancy** [LmeSzinc/StarRailCopilot#237]
### 你的功能请求是否与问题有关？

RT

### 解决方案

RT

**Comment by Asxcvbn** [comment]
似乎和这个 https://github.com/LmeSzinc/StarRailCopilot/issues/52 一致， 以下复制自我提到的issue中的用户提到的LmeSzinc的原话：

以下来自lme原话:
差距太大碰磁不了
一是用户体验层面，启动模拟器-启动游戏-执行任务-无任务关闭游戏，这都是自动的，用户只需要点开始，可以完全收到后台，桌面端还要一堆手动的准备任务才能开始
二是代码质量，研究透windows要有很深功力的，还包括win7 win10的不同版本 win11不同版本，它们的接口还有区别，我是搞不定，现在的这些就是网上搜的win32屎拼起来，达不到项目标准。相比之下模拟器连接alas和maa一起研究了两三年是比较成熟了
所以应该不会适配桌面的

**Comment by Luochancy** [comment]
> 似乎和这个 #52 一致， 以下复制自我提到的issue中的用户提到的LmeSzinc的原话：
> 
> 以下来自lme原话: 差距太大碰磁不了 一是用户体验层面，启动模拟器-启动游戏-执行任务-无任务关闭游戏，这都是自动的，用户只需要点开始，可以完全收到后台，桌面端还要一堆手动的准备任务才能开始 二是代码质量，研究透windows要有很深功力的，还包括win7 win10的不同版本 win11不同版本，它们的接口还有区别，我是搞不定，现在的这些就是网上搜的win32屎拼起来，达不到项目标准。相比之下模拟器连接alas和maa一起研究了两三年是比较成熟了 所以应该不会适配桌面的

其实应该还有种办法
通过无线/有线ADB直接操控移动端设备
因为咱是有看到用到了ADB和OCR所以就在想正在可不可行
就是手机还得到开发者模式开启模拟点击，也不算很简洁

**Comment by Asxcvbn** [comment]
adb好说，
分辨率能设置到1280x720的话（因为这个工具似乎只支持这个分辨率？）， 应该也可以用

这个的话自己也可以折腾吧= =分辨率只能靠你自己，然后adb那边可以考虑远程调试（wifi链接），usb线的方案的话也许得手动找一下serial（ 插上线 adb devices）

**Comment by Luochancy** [comment]
> @Luochancy adb好说， 分辨率能设置到1280x720的话（因为这个工具似乎只支持这个分辨率？）， 应该也可以用
> 
> 这个的话自己也可以折腾吧= =分辨率只能靠你自己，然后adb那边可以考虑远程调试（wifi链接），usb线的方案的话也许得手动找一下serial（ 插上线 adb devices）

是这样的没错
但更希望工具本身适配或者说开发出这种功能，这样也能方便其他玩家使用

**Comment by Asxcvbn** [comment]
> > @Luochancy adb好说， 分辨率能设置到1280x720的话（因为这个工具似乎只支持这个分辨率？）， 应该也可以用
> > 这个的话自己也可以折腾吧= =分辨率只能靠你自己，然后adb那边可以考虑远程调试（wifi链接），usb线的方案的话也许得手动找一下serial（ 插上线 adb devices）
> 
> 是这样的没错 但更希望工具本身适配或者说开发出这种功能，这样也能方便其他玩家使用

搜索了一下如何改分辨率：
一个做法是靠wm size，但是这个方案是全局的，意味着你用完铁道之后，正常使用设备的时候，需要再通过wm修改回来，这可能会带来一些麻烦和issue，比如怎么用完SRC我手机分辨率降低了？；或者一直连着设备不取下来了；同时每次链接可能会需要一些手机端手动设置（比如小米的usb调试（安全设置））；
然后adb连接：
现在的serial本来就需要手动获取，来针对不同的模拟器，不过加入一个选项（usb）似乎不是什么技术问题；

那么主要问题就是这个是否是作者有意向提供支持的用法了，尤其是考虑到目前理论上完全可以在不对SRC本身代码做任何修改的情况下连接手机。

**Comment by Luochancy** [comment]
> > > @Luochancy adb好说， 分辨率能设置到1280x720的话（因为这个工具似乎只支持这个分辨率？）， 应该也可以用
> > > 这个的话自己也可以折腾吧= =分辨率只能靠你自己，然后adb那边可以考虑远程调试（wifi链接），usb线的方案的话也许得手动找一下serial（ 插上线 adb devices）
> > 
> > 
> > 是这样的没错 但更希望工具本身适配或者说开发出这种功能，这样也能方便其他玩家使用
> 
> 搜索了一下如何改分辨率： 一个做法是靠wm size，但是这个方案是全局的，意味着你用完铁道之后，正常使用设备的时候，需要再通过wm修改回来，这可能会带来一些麻烦和issue，比如怎么用完SRC我手机分辨率降低了？；或者一直连着设备不取下来了；同时每次链接可能会需要一些手机端手动设置（比如小米的usb调试（安全设置））； 然后adb连接： 现在的serial本来就需要手动获取，来针对不同的模拟器，不过加入一个选项（usb）似乎不是什么技术问题；
> 
> 那么主要问题就是这个是否是作者有意向提供支持的用法了，尤其是考虑到目前理论上完全可以在不对SRC本身代码做任何修改的情况下连接手机。

不太清楚是什么情况，我手机通过无线adb无法被SRC控制
似乎还是需要配对码？
也就是还是要对其进行部分修改吧

**Comment by Asxcvbn** [comment]
@Luochancy  试试有线adb的adb devices里面会给的类似序列号的东西呢？顺便试试能不能进adb shell；

**Comment by Luochancy** [comment]
> @Luochancy 试试有线adb的adb devices里面会给的类似序列号的东西呢？顺便试试能不能进adb shell；

小米的机器
已经root
是可以进adb shell的

**Comment by Asxcvbn** [comment]
> > @Luochancy 试试有线adb的adb devices里面会给的类似序列号的东西呢？顺便试试能不能进adb shell；
> 
> 小米的机器 已经root 是可以进adb shell的

有log吗（）

**Comment by Luochancy** [comment]
> > > @Luochancy 试试有线adb的adb devices里面会给的类似序列号的东西呢？顺便试试能不能进adb shell；
> > 
> > 
> > 小米的机器 已经root 是可以进adb shell的
> 
> 有log吗（）

没截图（）
晚点再试试看顺便截图罢

**Comment by aaahai00** [comment]
PC端有PC的项目，虽然做个集合也不是不行，这个属实是没啥必要（想要的去三月七工具箱，这个是PC的集合）

**Comment by jerrita** [comment]
windows 可以加上 `use_mobile_platform -is_cloud 1 -platform_type CLOUD_THIRD_PARTY_MOBILE` 参数启动触屏模式，应该就能复用大部分安卓端的代码了

**Comment by aaahai00** [comment]
> windows 可以加上 `use_mobile_platform -is_cloud 1 -platform_type CLOUD_THIRD_PARTY_MOBILE` 参数启动触屏模式，应该就能复用大部分安卓端的代码了

这个项目是使用adb来控制手机及模拟器的，PC端调了的话还是要做些修改，重点是PC有人做了呀想用的去隔壁项目就行了

**Comment by jerrita** [comment]
> 这个项目是使用adb来控制手机及模拟器的，PC端调了的话还是要做些修改，重点是PC有人做了呀想用的去隔壁项目就行了

隔壁项目不能切屏，用触屏模式可以挂后台

**Comment by aaahai00** [comment]
> > 这个项目是使用adb来控制手机及模拟器的，PC端调了的话还是要做些修改，重点是PC有人做了呀想用的去隔壁项目就行了
> 
> 隔壁项目不能切屏，用触屏模式可以挂后台

怎么说呢我感觉你没看懂，PC端肯定是只能跑在PC端，系统问题他一定要在前台才可以点，最后的效果是一样的（电脑哪来的adb，你调成触屏一样得手动点啊）
当然实际上也不是没有解决方法，解决方法冗长而且麻烦（有一些软件还是收费的）最后可能还是没有本地多用户好用

不过我有点没看懂你这个触屏模式可以挂后台是什么意思，他可以无视窗口限制点吗，别到最后一样抢鼠标，我等会试试得了

（隔壁有告诉你怎么挂后台的，通过教程照做就可以了）

**Comment by LmeSzinc** [comment]
立项目的时候已经表示得很清楚了，不会添加
![~5$6EEUQY3MHFQ$E84WQJD9](https://github.com/LmeSzinc/StarRailCopilot/assets/37934724/66bb9316-ba19-4148-8344-3672f540e029)
