### ISSUE TITLE
Combat Prepare 提前退出

### ISSUE THREAD

**Issue by 5upernova-heng** [LmeSzinc/StarRailCopilot#24]
试了一下打本功能，好像偶尔会有点问题：
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/76626546/c599c5e3-d7f3-4e8b-9965-49021d85f38c)

在准备阶段的循环里面，配好队伍开始战斗，进入战斗画面之前，是没有开拓力界面的，导致没体力，提前退出了。
很怪，按理来说应该不会识别到 COMBAT_PREPARE 才对。

我在 screenshot 的时候把图片保存起来，结果之后没出现这个问题了。。。很怪。
如果需要提供更多信息请告诉我

**Comment by 5upernova-heng** [comment]
新的日志：
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/76626546/865b1b25-616d-445c-bef5-a9a270de8b8c)

最后一次截图：
![1687235776 0243957](https://github.com/LmeSzinc/StarRailCopilot/assets/76626546/62b9299f-901a-4414-b45f-0ac027773930)

可能是 COMBAT_PREPARE 和 COMBAT_TEAM_PREPARE 太像了

**Comment by bll19** [comment]
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/134405645/5b2924b9-29ac-47ad-acdd-4ff07a9d0b21)
我也遇到了相同的问题

**Comment by 5upernova-heng** [comment]
LGTM
