### ISSUE TITLE
启动SRC的时候自动运行调度器 和 通过SRC启动/关闭模拟器

### ISSUE THREAD

**Issue by 3000degreesCelsius** [LmeSzinc/StarRailCopilot#240]
### 你的功能请求是否与问题有关？

目的是简化操作，当SRC启动时自动拉起模拟器，并运行调度器，当任务结束时候关闭模拟器
这样只需启动SRC就可以全自动完成日常任务

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/StarRailCopilot/issues/118#issuecomment-1741768728
