### ISSUE TITLE
显示忆庭与虚构叙事的剩余时间

### ISSUE THREAD

**Issue by 3000degreesCelsius** [LmeSzinc/StarRailCopilot#241]
### 你的功能请求是否与问题有关？

在仪表盘上显示忆庭与虚构叙事的剩余时间

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/StarRailCopilot/issues/160#issuecomment-1762860125

**Comment by aaahai00** [comment]
现在时间都延长到一个多月了，想起来就打不就完了，实在不行定个日程或者闹钟，不过添加这功能确实能方便不少（我的建议是添加一个自定义计时器，显示什么内容和时间自定义，归零自动回满）
