### ISSUE TITLE
模拟宇宙命途过多导致选择不了部分命途

### ISSUE THREAD

**Issue by Little-Vegetable-Bird** [LmeSzinc/StarRailCopilot#243]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

模拟宇宙命途过多导致选择不了部分命途

### 如何复现

模拟宇宙命途选择页面，如图如果在src选择欢愉命途那么久识别不到一直卡在命途选择界面，如果手动点击右边的箭头就能识别到欢愉命途并选择

### 截图

![屏幕截图 2023-12-28 165840](https://github.com/LmeSzinc/StarRailCopilot/assets/116429705/c4a8c521-dfd2-49eb-81a0-4bc0975986da)
![屏幕截图 2023-12-28 165958](https://github.com/LmeSzinc/StarRailCopilot/assets/116429705/7630652f-6812-4f4a-a87a-af0932c9b63a)

**Comment by aaahai00** [comment]
#252（问题类似）
