### ISSUE TITLE
DungeonNavList.select_row 选择第二页的 Nav 时有概率选错

### ISSUE THREAD

**Issue by 5upernova-heng** [LmeSzinc/StarRailCopilot#26]
我知道现在只支持第一页一部分副本的导航，但我想这 select_row 一部分应该写完了。
我准备写 进深渊第一层 + 使用两次秘技 的每日任务，碰到了这个问题。

滑动还没有稳定之前就识别 & 点击了
![1687328311 9596653](https://github.com/LmeSzinc/StarRailCopilot/assets/76626546/94e1178a-067a-42ca-9189-723baccd3887)

![2023-06-21_14-21-57-259182](https://github.com/LmeSzinc/StarRailCopilot/assets/76626546/948fce54-3b84-4dfd-a2af-a96e87071073)

**Comment by LmeSzinc** [comment]
把检测区域和滑动区域改到不含横幅的地方

**Comment by 5upernova-heng** [comment]
> 把检测区域和滑动区域改到不含横幅的地方

横幅指的是哪一部分？

**Comment by LmeSzinc** [comment]
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/37934724/4a4a94d4-3cd8-4bbb-853b-761bb6d9234f)

**Comment by 5upernova-heng** [comment]
> ![image](https://user-images.githubusercontent.com/37934724/248269953-4a4a94d4-3cd8-4bbb-853b-761bb6d9234f.png)

我可能表达得不是很清楚。我指的是左侧的 Nav 栏。
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/76626546/7f8aeffe-b387-420b-8274-2f14752f5e17)
Nav 栏截图 OCR 的时候，Nav 栏还处于拖拽完恢复的状态。导致识别的位置不对。
比如上图，识别“忘却之庭”。点击的时候“忘却之庭”的位置已经和截图的时候的位置不一样了
