### ISSUE TITLE
在歷戰餘響功能中新增支援角色的選項

### ISSUE THREAD

**Issue by seriaati** [LmeSzinc/StarRailCopilot#296]
### 你的功能请求是否与问题有关？

歷戰餘響副本難度較高，需要好友角色支援，否則容易將戰鬥時間拉到太長導致超時，或是隊伍全軍覆沒導致戰鬥失敗。

### 解决方案

像每日副本一樣，可以在歷戰餘響中選擇支援角色。

**Comment by LmeSzinc** [comment]
目前游戏无法指定选择某个助战，助战列表是随机刷新的，包括好友也是随机刷新的，因此助战默认是拖油瓶角色，加入队伍不会有帮助。

**Comment by aaahai00** [comment]
> 目前游戏无法指定选择某个助战，助战列表是随机刷新的，包括好友也是随机刷新的，因此助战默认是拖油瓶角色，加入队伍不会有帮助。

后期铁道那边会有支援置顶，直接选择列表第一个角色就可以

**Comment by seriaati** [comment]
2.0 版本更新會有置頂角色功能吧

**Comment by aaahai00** [comment]
> 目前游戏无法指定选择某个助战，助战列表是随机刷新的，包括好友也是随机刷新的，因此助战默认是拖油瓶角色，加入队伍不会有帮助。

目前已经可以置顶支援角色了

**Comment by aaahai00** [comment]
> 2.0 版本更新會有置頂角色功能吧

的确更新了
