### ISSUE TITLE
副本传送错误

### ISSUE THREAD

**Issue by aaahai00** [LmeSzinc/StarRailCopilot#332]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

总结：
也许大部分副本都有名字出来了传送没出来的问题，只是触发概率低，而且能自动解决而不被察觉而已

### 预期行为

正常传送

### 相关 Logs
删除了多余部分
全部复制出来超过字数限制了，所以以文件方式发在这里
[野焰之径·侵蚀隧洞.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327439/default.txt)
[霜晶之形·凝滞虚影.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327440/default.txt)
[虚无之蕾（丹鼎司）.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327441/default.txt)
[虚无之蕾（大矿区）.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327442/default.txt)
[以太之蕾.匹诺康尼.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327443/default.txt)
重测
[霜晶之形·凝滞虚影重测.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327735/default.txt)
我等到异常处理重启游戏再停止，这个是绝对完整的了

### 截图
霜晶之形·凝滞虚影：
![Screenshot_20240219-034622](https://github.com/LmeSzinc/StarRailCopilot/assets/108205808/7bc9aa99-0cc1-4c44-9606-36d4ca6b8e25)
野焰之径·侵蚀隧洞
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/108205808/5c5ff33d-c822-4f87-82a1-9ffbd68e2a15)
重测
霜晶之形·凝滞虚影：
![屏幕截图 2024-02-19 151421](https://github.com/LmeSzinc/StarRailCopilot/assets/108205808/cf49a714-60a9-4d07-b49d-18d4db591e42)

### 还有别的吗？

同谐之蕾·匹诺康尼：
大概原因是正好滑动到“[白日梦]酒店-梦境”这行字刚出现的地方，但是传送没有出来，所以无法传送
像这样
![屏幕截图 2024-02-19 145854](https://github.com/LmeSzinc/StarRailCopilot/assets/108205808/17bb3895-ff16-4d82-bd62-2b1d2d276560)
虚无之蕾（大矿区）：滑一半卡住了
[虚无之蕾（丹鼎司）]，
[霜晶之形·凝滞虚影 ] ，
[野焰之径·侵蚀隧洞] ：副本名字出来了传送键没出来
霜晶之形·凝滞虚影  ：重新测试，问题一致

[目前发现的触发概率不高，且可以通过异常处理自动解决，只是异常处理触发时间过久，需要优化一下]

**Comment by aaahai00** [comment]
另外卡死设置的时间有点过长了，需要等很久才能等到异常处理

**Comment by aaahai00** [comment]
我也想到一个简单粗暴的解决方法，他没有识别到画面变化的时候直接往下滑一点再点击，或者直接关闭页面重新打开~~，你总不能次次都卡住吧~~

**Comment by LmeSzinc** [comment]
有问题发log和截图

**Comment by aaahai00** [comment]
> 有问题发log和截图

截图和log上边有

**Comment by aaahai00** [comment]
> 有问题发log和截图
删除了多余部分，完整的看上面
[野焰之径·侵蚀隧洞.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327439/default.txt)
[霜晶之形·凝滞虚影.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327440/default.txt)
[虚无之蕾（丹鼎司）.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327441/default.txt)
[虚无之蕾（大矿区）.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327442/default.txt)
[以太之蕾.匹诺康尼.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14327443/default.txt)
图片大体都差不多，~~前面测的忘截了~~
霜晶之形·凝滞虚影：
![Screenshot_20240219-034622](https://github.com/LmeSzinc/StarRailCopilot/assets/108205808/7bc9aa99-0cc1-4c44-9606-36d4ca6b8e25)
野焰之径·侵蚀隧洞
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/108205808/5c5ff33d-c822-4f87-82a1-9ffbd68e2a15)

因为不想让他重启游戏，所以发现无法传送的时候就手动停止了

**Comment by aaahai00** [comment]
未删除多余部分log
以太之蕾.匹诺康尼
[2024-02-19_198.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14323863/2024-02-19_198.txt)
虚无之蕾（大矿区）
[2024-02-19_198 - 副本.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14324098/2024-02-19_198.-.txt)
虚无之蕾（丹鼎司）
[2024-02-19_198 1.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14324141/2024-02-19_198.1.txt)
霜晶之形·凝滞虚影
[2024-02-19_198 -2.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14324165/2024-02-19_198.-2.txt)
野焰之径·侵蚀隧洞
[2024-02-19_198 3.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14324201/2024-02-19_198.3.txt)

**Comment by aaahai00** [comment]
> 有问题发log和截图

重新编辑了一下问题，精简了内容，
单独测试霜晶之形的内容也一起编辑进去了

**Comment by LmeSzinc** [comment]
#335

**Comment by aaahai00** [comment]
打的时候感觉这个问题还是时有发生，我有空抽个时间来验证一下，如果验证还是有问题我会重新编辑这个问题并重新打开

**Comment by aaahai00** [comment]
> 打的时候感觉这个问题还是时有发生，我有空抽个时间来验证一下，如果验证还是有问题我会重新编辑这个问题并重新打开

目前已测试所有的行迹材料副本和遗器副本，均已测试三次（部分反馈有问题的测试了六次以上）未发现问题
突破材料随机测试了五六个没有问题，金花未测试，但应该没有问题
有人反馈周本也有该问题（但我次数打完了，没法测，留在下一周吧）
