### ISSUE TITLE
一个安装上的问题

### ISSUE THREAD

**Issue by partialint** [LmeSzinc/StarRailCopilot#336]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

很神奇的
我双击打开src.exe没反应然后我就“以管理员打开”，还是没反应。我就打开cmd 用start 指令打开，报错A JavaScript erroroccurred in the main process。然后我用PowerShell里用start，结果就成功打开了！这是我的电脑的问题还是什么兼容性问题。

### 如何复现

和描述一致

### 预期行为

双击打开src.exe

### 截图

![image](https://github.com/LmeSzinc/StarRailCopilot/assets/131539747/2958937e-bb6f-4616-9657-adc07146907f)
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/131539747/34b05114-4103-4e57-812d-298ede78c7cb)

### 还有别的吗？

笔记本，win11家庭中文版

**Comment by partialint** [comment]
在属性勾选一下“解除锁定”，就好了
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/131539747/338a6f39-8519-418c-8276-c848e733259e)

**Comment by aaahai00** [comment]
> 在属性勾选一下“解除锁定”，就好了
> ![image](https://github.com/LmeSzinc/StarRailCopilot/assets/131539747/338a6f39-8519-418c-8276-c848e733259e)
> 

解决了记得把问题关闭了
