### ISSUE TITLE
Blessing Settings in Simulated Universe is in chinese

### ISSUE THREAD

**Issue by Geeblish** [LmeSzinc/StarRailCopilot#340]
### Before you asking

- [ ] I have searched the existing issues
- [x] I spend at least 5 minutes for thinking and preparing
- [x] I am using the latest version of SRC

### Describe the bug

Text in Custom presets for blessing in Simulated Universe tab is in chinese while using english src. 

### To Reproduce

1. Go to src
2. Click on simulated universe
3. Scroll down to blessing settings
4. Change dropdown to custom
5. See error

### Expected behavior

Filter should be in English

### Screenshots

![src_ZJAp2Hr7Uf](https://github.com/LmeSzinc/StarRailCopilot/assets/60635068/6b8120de-c9f5-4064-a3f8-48639f480716)

### Anything else?

Not sure if this will affect gameplay if the chinese is autotranslated to english

My solution was looking at the chinese game and changing the text line manually

**Comment by LmeSzinc** [comment]
Default filter is the same as `preset`, it's a format demonstration, no need to change their languages if you don't have anything customized. To customize, filter strings accept blessing names from all supported languages (zh-CN, en-US, ja-JP, zh-TW, es-ES), you can find the names from any game wikis.

**Comment by Geeblish** [comment]
So basically what it's doing is setting the priority? So if I do something like
Resonance Formation: Anicca > Resonance Formation: Anatta > Resonance Formation: Terminal Nirvana
Anicca will be chosen first?

**Comment by LmeSzinc** [comment]
yep
