### ISSUE TITLE
OCR Failure due to button inconsistency 按钮位置不一致导致识别失效

### ISSUE THREAD

**Issue by JerryLingjieMei** [LmeSzinc/StarRailCopilot#344]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I am using the latest version of SRC

### Describe the bug

![0](https://github.com/LmeSzinc/StarRailCopilot/assets/35284045/f17fc3e0-07cf-464a-92a3-d3934cec9233)
图0为直接进入模拟宇宙8最终关的按钮布局

![1](https://github.com/LmeSzinc/StarRailCopilot/assets/35284045/3b0dc857-37e0-455d-a8ef-3fc2ad50ee58)
图1为重新加载模拟宇宙8最终观的按钮布局

可以看到两者的右下按钮并不重合（图0向左偏移） 从而导致 #338 中战绩点识别失败（图0不可以识别 图1可以识别）

### To Reproduce

使用MuMu12 模拟器 1280x720 240 dpi Vulkan mode, window 系统

**Comment by LmeSzinc** [comment]
#369
