### ISSUE TITLE
每次出现 限时提前解锁 那么就就不能自动打副本了

### ISSUE THREAD

**Issue by rosebudgrave** [LmeSzinc/StarRailCopilot#348]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

每次出现 限时提前解锁 那么就就不能自动打副本了

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by rosebudgrave** [comment]
![c3bcbc3fe810e261ab0ad83e715a213](https://github.com/LmeSzinc/StarRailCopilot/assets/45752666/5c48a494-d2b8-47e6-85ee-5130a7bbf73b)
![c3bcbc3fe810e261ab0ad83e715a213](https://github.com/LmeSzinc/StarRailCopilot/assets/45752666/a57128f9-d1d6-4844-a6cb-67049b541203)

**Comment by aaahai00** [comment]
这个不在新地图里面，手动解锁吧

**Comment by aaahai00** [comment]
按照开发者之前发过的评论看来是不会专门修这个东西的，只能说做好被拒的准备
