### ISSUE TITLE
双倍花活动似乎没被检测到

### ISSUE THREAD

**Issue by Asxcvbn** [LmeSzinc/StarRailCopilot#370]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

![图片](https://github.com/LmeSzinc/StarRailCopilot/assets/63904802/f7be7841-e678-4612-85a8-2433272d02c8)
如图，当前每日设置为日常刷智识（铆钉镇），双倍花时候刷同协（机械聚落），而令其进行每日时，它选择了智识
INFO     21:16:08.794 │ Click (1092,  473) @                                       
         DungeonList(Calyx_Crimson_Erudition_Jarilo_RivetTown)    

但是在ocr中可以看到
2024-03-16 21:16:06.746 | INFO | [OCR_DUNGEON_LIST 0.608s] ['2 今日双倍奖励剩余次数：', '12/12',                       
'丰饶之蕾·拟造花萼（赤）', '●边缘通路', '10', '传送', '50', '智识之蕾·拟造花萼（赤）', '铆钉镇', '10', '传送', '50',   
'同谐之蕾·拟造花萼（赤）', '机械聚落', '10', '传送']     
我不确定有没有识别到双倍花，不排除它就没识别到。

log中还可以看到 2024-03-16 19:20 左右SRC在刷DungeonList(Stagnant_Shadow_Doom) ，为景园卡夫卡的突破材料，当时日常设置为突破材料，而双倍花设置为同协

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

正确识别双倍花

### 截图

[2024-03-16_src.txt](https://github.com/LmeSzinc/StarRailCopilot/files/14623783/2024-03-16_src.txt)

**Comment by LmeSzinc** [comment]
#369
