### ISSUE TITLE
src启动模拟器后无法启动云星铁

### ISSUE THREAD

**Issue by icateav** [LmeSzinc/StarRailCopilot#379]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

src启动模拟器后无法继续启动云星铁

### 如何复现

启动src，令其自动启动模拟器，模拟器停留在模拟器桌面，任务停留在异常处理，没有继续自动运行

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     14:20:04.827 │ Start scheduler loop: src                                  
INFO     14:20:04.829 │ [Lang] cn                                                  
INFO     14:20:04.833 │ Bind task ['Alas']                                         
INFO     14:20:04.834 │ Pending tasks: ['Restart', 'BattlePass', 'DailyQuest',     
         'Freebies', 'DataUpdate', 'Weekly', 'Dungeon']                            
INFO     14:20:04.835 │ [Task] Restart (Enable, 2024-03-23 04:00:00)               
INFO     14:20:04.835 │ Bind task ['Alas', 'Restart']                              
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     14:20:07.972 │ DEVICE                                                     
INFO     14:20:07.983 │ [AdbBinary]                                                
         D:\插件\StarRailCopilot\toolkit\Lib\site-packages\adbutils\binaries\adb.ex
         e                                                                         
INFO     14:20:07.984 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     14:20:07.985 │ <<< DETECT DEVICE >>>                                      
INFO     14:20:07.985 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     14:20:07.989 │ No available devices                                       
INFO     14:20:10.035 │ cannot connect to 127.0.0.1:16448:                         
         由于目标计算机积极拒绝，无法连接。 (10061)                                
INFO     14:20:10.036 │ cannot connect to 127.0.0.1:16448:                         
         由于目标计算机积极拒绝，无法连接。 (10061)                                
WARNING  14:20:10.037 │ No such device exists, please restart the emulator or set a
         correct serial                                                            
───────────────────────────── FIND EMULATOR INSTANCE ──────────────────────────────
INFO     14:20:10.039 │ FIND EMULATOR INSTANCE                                     
INFO     14:20:10.052 │ MuMuPlayer12(serial="127.0.0.1:16384",                     
         name="MuMuPlayer-12.0-0",                                                 
         path="D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe")                       
INFO     14:20:10.055 │ MuMuPlayer12(serial="127.0.0.1:16416",                     
         name="MuMuPlayer-12.0-1",                                                 
         path="D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe")                       
INFO     14:20:10.056 │ MuMuPlayer12(serial="127.0.0.1:16448",                     
         name="MuMuPlayer-12.0-2",                                                 
         path="D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe")                       
──────────────────────────────── EMULATOR INSTANCE ────────────────────────────────
INFO     14:20:10.057 │ EMULATOR INSTANCE                                          
INFO     14:20:10.058 │ Found emulator instance:                                   
         MuMuPlayer12(serial="127.0.0.1:16448", name="MuMuPlayer-12.0-2",          
         path="D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe")                       
═════════════════════════════════ EMULATOR START ══════════════════════════════════
INFO     14:20:10.059 │ EMULATOR START                                             
────────────────────────────────── EMULATOR STOP ──────────────────────────────────
INFO     14:20:10.060 │ EMULATOR STOP                                              
INFO     14:20:10.435 │ Execute: "D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe" -v 2
───────────────────────────────── EMULATOR START ──────────────────────────────────
INFO     14:20:13.306 │ EMULATOR START                                             
INFO     14:20:13.307 │ Current window: 67108                                      
INFO     14:20:22.004 │ New window showing up: 263740, focus back                  
INFO     14:20:31.194 │ Emulator online: AdbDevice(127.0.0.1:16448, device)        
INFO     14:20:31.568 │ Command ping: pong                                         
[src] exited. Reason: Manual stop

═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     14:26:56.424 │ Start scheduler loop: src                                  
INFO     14:26:56.427 │ [Lang] cn                                                  
INFO     14:26:56.432 │ Bind task ['Alas']                                         
INFO     14:26:56.433 │ Pending tasks: ['Restart', 'BattlePass', 'DailyQuest',     
         'Freebies', 'DataUpdate', 'Weekly', 'Dungeon']                            
INFO     14:26:56.434 │ [Task] Restart (Enable, 2024-03-23 04:00:00)               
INFO     14:26:56.435 │ Bind task ['Alas', 'Restart']                              
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     14:26:57.615 │ DEVICE                                                     
INFO     14:26:57.644 │ [AdbBinary]                                                
         D:\插件\StarRailCopilot\toolkit\Lib\site-packages\adbutils\binaries\adb.ex
         e                                                                         
INFO     14:26:57.645 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     14:26:57.646 │ <<< DETECT DEVICE >>>                                      
INFO     14:26:57.646 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     14:26:57.648 │ No available devices                                       
INFO     14:26:57.648 │ Here are the devices detected but unavailable              
INFO     14:26:57.649 │ 127.0.0.1:16448 (offline)                                  
WARNING  14:26:57.650 │ Device 127.0.0.1:16448 is offline, disconnect it before    
         connecting                                                                
INFO     14:26:57.653 │ disconnected 127.0.0.1:16448                               
INFO     14:26:59.707 │ cannot connect to 127.0.0.1:16448:                         
         由于目标计算机积极拒绝，无法连接。 (10061)                                
INFO     14:26:59.708 │ cannot connect to 127.0.0.1:16448:                         
         由于目标计算机积极拒绝，无法连接。 (10061)                                
WARNING  14:26:59.709 │ No such device exists, please restart the emulator or set a
         correct serial                                                            
───────────────────────────── FIND EMULATOR INSTANCE ──────────────────────────────
INFO     14:26:59.710 │ FIND EMULATOR INSTANCE                                     
INFO     14:26:59.728 │ MuMuPlayer12(serial="127.0.0.1:16384",                     
         name="MuMuPlayer-12.0-0",                                                 
         path="D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe")                       
INFO     14:26:59.729 │ MuMuPlayer12(serial="127.0.0.1:16416",                     
         name="MuMuPlayer-12.0-1",                                                 
         path="D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe")                       
INFO     14:26:59.730 │ MuMuPlayer12(serial="127.0.0.1:16448",                     
         name="MuMuPlayer-12.0-2",                                                 
         path="D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe")                       
──────────────────────────────── EMULATOR INSTANCE ────────────────────────────────
INFO     14:26:59.731 │ EMULATOR INSTANCE                                          
INFO     14:26:59.732 │ Found emulator instance:                                   
         MuMuPlayer12(serial="127.0.0.1:16448", name="MuMuPlayer-12.0-2",          
         path="D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe")                       
═════════════════════════════════ EMULATOR START ══════════════════════════════════
INFO     14:26:59.733 │ EMULATOR START                                             
────────────────────────────────── EMULATOR STOP ──────────────────────────────────
INFO     14:26:59.734 │ EMULATOR STOP                                              
INFO     14:27:00.165 │ Execute: "D:/app/MuMuPlayer-12.0/shell/MuMuPlayer.exe" -v 2
───────────────────────────────── EMULATOR START ──────────────────────────────────
INFO     14:27:03.498 │ EMULATOR START                                             
INFO     14:27:03.498 │ Current window: 67108                                      
INFO     14:27:14.517 │ Emulator online: AdbDevice(127.0.0.1:16448, device)        
INFO     14:27:14.918 │ Command ping: pong                                         
INFO     14:27:17.197 │ New window showing up: 329290, focus back
```

**Comment by LmeSzinc** [comment]
上传完整log

**Comment by icateav** [comment]
──────────────────────────────── EMULATOR START ─────────────────────────────────
INFO     19:13:11.200 │ EMULATOR START                                           
INFO     19:13:11.202 │ Current window: 66052                                    
INFO     19:13:23.015 │ Emulator online: AdbDevice(127.0.0.1:16448, device)      
INFO     19:13:23.442 │ Command ping: pong                                       
INFO     19:14:03.604 │ New window showing up: 329950, focus back                
WARNING  19:18:11.621 │ Emulator start timeout                                   
════════════════════════════════════ DEVICE ═════════════════════════════════════
INFO     19:18:11.623 │ DEVICE                                                   
INFO     19:18:11.624 │ [AdbBinary]                                              
         D:\插件\StarRailCopilot\toolkit\Lib\site-packages\adbutils\binaries\adb.
         exe                                                                     
INFO     19:18:11.625 │ <<< DETECT DEVICE >>>                                    
INFO     19:18:11.626 │ Here are the available devices, copy to                  
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"       
INFO     19:18:11.627 │ 127.0.0.1:16416                                          
INFO     19:18:11.628 │ 127.0.0.1:16448                                          
INFO     19:18:11.628 │ 127.0.0.1:7555                                           
INFO     19:18:11.631 │ already connected to 127.0.0.1:16448                     
INFO     19:18:11.632 │ [AdbDevice] AdbDevice(serial=127.0.0.1:16448)            
INFO     19:18:11.633 │ [Server] CN-Official                                     
INFO     19:18:11.633 │ [PackageName] com.miHoYo.cloudgames.hkrpg                
INFO     19:18:11.634 │ [Lang] cn                                                
INFO     19:18:11.643 │ [nemud.app_keep_alive] false                             
INFO     19:18:11.644 │ Skip task `Restart` at scheduler start                   
INFO     19:18:11.646 │ Delay task `Restart` to 2024-04-02 04:00:00              
         (server_update='04:00')                                                 
INFO     19:18:11.648 │ Bind task ['Alas', 'Restart']                            
INFO     19:18:11.648 │ Save config ./config\src.json,                           
         Restart.Scheduler.NextRun=datetime.datetime(2024, 4, 2, 4, 0)           
INFO     19:18:11.654 │ [Lang] cn                                                
INFO     19:18:11.667 │ Bind task ['Alas']                                       
INFO     19:18:11.668 │ Pending tasks: ['BattlePass', 'DailyQuest', 'Assignment',
         'Freebies', 'DataUpdate', 'Weekly', 'Dungeon']                          
INFO     19:18:11.669 │ [Task] BattlePass (Enable, 2024-04-01 04:00:00)          
INFO     19:18:11.670 │ Bind task ['Alas', 'BattlePass']                         
INFO     19:18:11.671 │ Scheduler: Start task `BattlePass`                       
═════════════════════════════════════════════════════════════════════════════════
                                   BATTLEPASS                                    
═════════════════════════════════════════════════════════════════════════════════
INFO     19:18:12.364 │ [u2.Device] Device(atx_agent_url=http://127.0.0.1:63716) 
INFO     19:18:12.381 │ [Device Orientation] 1 (HOME key on the right)           
INFO     19:18:12.383 │ [Screen_size] 1280x720                                   
INFO     19:18:12.383 │ <<< SCRCPY SERVER START >>>                              
INFO     19:18:12.386 │ Create server stream                                     
INFO     19:18:12.574 │ b'[server] INFO: Device: Xiaomi 2206122SC (Android 12)\n'
INFO     19:18:12.576 │ Create video socket                                      
INFO     19:18:12.683 │ Create control socket                                    
INFO     19:18:12.685 │ Fetch device info                                        
INFO     19:18:12.686 │ [Scrcpy Device] 2206122SC                                
INFO     19:18:12.687 │ [Scrcpy Resolution] (1280, 720)                          
INFO     19:18:12.688 │ Start video stream loop thread                           
INFO     19:18:12.690 │ Scrcpy server is up                                      
INFO     19:18:14.037 │ [Screen_size] 1280x720                                   
INFO     19:18:15.652 │ <<< UI ENSURE >>>                                        
INFO     19:18:15.653 │ UI get current page                                      
INFO     19:18:15.876 │ Unknown ui page                                          
INFO     19:18:16.038 │ [Package_name] com.teslacoilsw.launcher                  
WARNING  19:18:16.039 │ Game not running                                         
INFO     19:18:16.040 │ Task call: Restart                                       
INFO     19:18:16.043 │ Bind task ['Alas', 'BattlePass']                         
INFO     19:18:16.044 │ Save config ./config\src.json,                           
         Restart.Scheduler.NextRun=datetime.datetime(2024, 4, 1, 19, 18, 16),    
         Restart.Scheduler.Enable=True                                           
INFO     19:18:16.050 │ Scheduler: End task `BattlePass`                         
INFO     19:18:16.051 │ [Lang] cn                                                
INFO     19:18:16.061 │ Bind task ['Alas']                                       
INFO     19:18:16.062 │ Pending tasks: ['Restart', 'BattlePass', 'DailyQuest',   
         'Assignment', 'Freebies', 'DataUpdate', 'Weekly', 'Dungeon']            
INFO     19:18:16.063 │ [Task] Restart (Enable, 2024-04-01 19:18:16)             
INFO     19:18:16.064 │ Bind task ['Alas', 'Restart']                            
INFO     19:18:16.078 │ Scheduler: Start task `Restart`  

原来不是打不开是要等个5分钟左右 那没事了
