### ISSUE TITLE
如何添加插件？

### ISSUE THREAD

**Issue by Aues6uen11Z** [LmeSzinc/StarRailCopilot#385]
SRC减少了对于碧蓝的耦合，现在对崩铁的耦合怎么样，添加插件还需要像ALAS那样写Bridge吗？我想把这个界面做成SRC插件https://github.com/Aues6uen11Z/HonkaiHelper

**Comment by muxifn** [comment]
我也再找 看有没干净的SRC框架 - -

**Comment by yanang007** [comment]
看起来开发者应该是有意向开放相关接口的，但是根据开发路线图，目前工作重心应该还是在优化SRC本身上。所以我相信现阶段这个功能应该属于feature request。
