### ISSUE TITLE
使用夜神模拟器以默认设置从总览运行调度器会在委托卡住，他选了人但是不派出去，我给他点击派出去之后，他会选择下一个任务选择人员准备调派，但是还是不会派出去，然后卡住重启循环

### ISSUE THREAD

**Issue by qtweftq** [LmeSzinc/StarRailCopilot#389]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

INFO     01:58:42.101 │ ASSIGNMENT INLIST                                          
INFO     01:58:42.101 │ Check assignment inlist:                                   
         AssignmentEntry(The_Invisible_Hand)                                       
INFO     01:58:42.107 │ Insight row: AssignmentEntry(The_Invisible_Hand), index=11 
INFO     01:58:42.255 │ [OCR_ASSIGNMENT_ENTRY_LIST 0.147s] ['阿卡夏记录',          
         '无名之地，无名之人', '看不见的手']                                       
INFO     01:58:42.257 │ [OCR_ASSIGNMENT_ENTRY_LIST matched]                        
         [AssignmentEntry(Akashic_Records),                                        
         AssignmentEntry(Nameless_Land_Nameless_People),                           
         AssignmentEntry(The_Invisible_Hand)]                                      
INFO     01:58:42.257 │ [AssignmentEntryList] 9 - 11                               
INFO     01:58:42.258 │ Select row: AssignmentEntry(The_Invisible_Hand)            
INFO     01:58:42.259 │ Click ( 267,  345) @ AssignmentEntry(The_Invisible_Hand)   
INFO     01:58:42.707 │ Row selected at AssignmentEntry(The_Invisible_Hand)        
INFO     01:58:42.710 │ [AssignmentStatus] DISPATCHABLE                            
INFO     01:58:42.712 │ Click (1080,  574) @ EMPTY_SLOT                            
INFO     01:58:43.110 │ Click ( 178,  245) @ CHARACTER_1                           
INFO     01:58:43.162 │ Click ( 292,  285) @ CHARACTER_2                           
INFO     01:59:43.191 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L116 spawn_main()                                      
                   spawn.py L129 _main()                                           
                 process.py L314 _bootstrap()                                      
                 process.py L108 run()                                             
         process_manager.py L149 run_process()                                     
                    alas.py L297 loop()                                            
                    alas.py  L81 run()                                             
                     src.py  L47 assignment()                                      
              assignment.py  L46 run()                                             
              assignment.py L111 _check_inlist()                                   
                dispatch.py  L63 dispatch()                                        
                dispatch.py  L89 _select_characters()                              
                  device.py L112 screenshot()                                      
                  device.py L148 stuck_record_check()                              
                  device.py  L43 show_function_call()                              
WARNING  01:59:43.193 │ Wait too long                                              
WARNING  01:59:43.193 │ Waiting for {'CHARACTER_LIST', 'CONFIRM_ASSIGNMENT'}       
INFO     01:59:43.215 │ [Package_name] com.miHoYo.hkrpg                            
ERROR    01:59:43.215 │ GameStuckError: Wait too long                              
WARNING  01:59:43.216 │ Saving error: ./log/error/1711562383216                    
WARNING  01:59:43.318 │ Game stuck, com.miHoYo.hkrpg will be restarted in 10       
         seconds                                                                   
WARNING  01:59:43.319 │ If you are playing by hand, please stop Alas               
INFO     01:59:43.320 │ Task call: Restart                                         
INFO     01:59:43.323 │ Bind task ['Alas', 'Assignment']                           
INFO     01:59:43.323 │ Save config ./config\src.json,                             
         Restart.Scheduler.NextRun=datetime.datetime(2024, 3, 28, 1, 59, 43),      
         Restart.Scheduler.Enable=True                                             
INFO     01:59:53.329 │ Scheduler: End task `Assignment`                           
CRITICAL 01:59:53.330 │ Task `Assignment` failed 3 or more times.                  
CRITICAL 01:59:53.330 │ Possible reason #1: You haven't used it correctly. Please  
         read the help text of the options.                                        
CRITICAL 01:59:53.331 │ Possible reason #2: There is a problem with this task.     
         Please contact developers or try to fix it yourself.                      
CRITICAL 01:59:53.332 │ Request human takeover                                     
ERROR    01:59:53.333 │ Error notify is not supported yet                          

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![20240328020245](https://github.com/LmeSzinc/StarRailCopilot/assets/162488580/c74f6c62-1902-4756-bbb7-d5cadfd4db93)

**Comment by mikezhl** [comment]
我也遇到同样的问题，mumu12模拟器，估计是电脑太卡了，现在百分百卡在这里
