### ISSUE TITLE
无法识别虚无之蕾

### ISSUE THREAD

**Issue by FireTomcat** [LmeSzinc/StarRailCopilot#398]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

使用夜神模拟器，在进行每日副本时选择虚无之蕾·丹鼎司，在执行时会无法识别出正确的，然后无限重启，陷入循环（所有多选项的都无法进行）

### 如何复现

1. 前往 '每日副本'
2. 点击 '虚无之蕾·丹鼎司'
3. 执行 '任务'
4. 出现问题

### 截图

![image](https://github.com/LmeSzinc/StarRailCopilot/assets/91539645/e213c2fe-6579-463b-b6d3-d73af4a0fc80)

**Comment by wing1215** [comment]
没有解锁传送点，不能使用提前解锁功能开启，因为他需要按照顺序识别副本，建议把所有没有开启的花蕾，都开启了，就可以了
