### ISSUE TITLE
模拟宇宙打满的情况下无法自动参加三倍活动

### ISSUE THREAD

**Issue by Dead-Universe** [LmeSzinc/StarRailCopilot#412]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

模拟宇宙打满的情况下无法自动参加三倍活动
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/60636914/8b5e410d-567e-486f-98a4-72c6a0341eab)

已经勾选“参与双倍内圈仪器活动”和“使用开拓力刷内圈遗器”
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/60636914/0ca5890a-e261-49cf-a243-4478cc0bb232)

**Comment by aaahai00** [comment]
是不是你体力没了才不打的

**Comment by Dead-Universe** [comment]
好像是的
