### ISSUE TITLE
手动安装的SRC自动更新失败

### ISSUE THREAD

**Issue by TiSpH** [LmeSzinc/StarRailCopilot#425]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

在 UPDATE ALAS 时脚本会把 git url 设置成 `global` 字符串，而非 `https://github.com/LmeSzinc/StarRailCopilot`。导致后续更新失败。
<img width="820" alt="Screenshot 2024-04-19 at 9 13 48 PM" src="https://github.com/LmeSzinc/StarRailCopilot/assets/14122965/4a392462-88ea-4c7d-958d-4059e24a556a">
正常应该这样：
<img width="818" alt="Screenshot 2024-04-19 at 9 18 11 PM" src="https://github.com/LmeSzinc/StarRailCopilot/assets/14122965/1ede1b4d-a006-4215-902f-8229d0cf50fe">

### 如何复现

1. 按照[手动安装教程](https://github.com/LmeSzinc/StarRailCopilot/wiki/Installation_cn#手动安装教程)安装SRC
2. 启动SRC
3. 等待自动更新
4. 出现问题

### 还有别的吗？

操作系统: macOS Sonoma 14.4.1
Conda 版本: 24.1.2
Python 版本: 3.10.10
是否使用 git-over-cdn: 否

**Comment by LmeSzinc** [comment]
上传完整的 log/*_gui.txt

**Comment by TiSpH** [comment]
> 上传完整的 log/*_gui.txt

[2024-04-19_gui.txt](https://github.com/LmeSzinc/StarRailCopilot/files/15057810/2024-04-19_gui.txt)

**Comment by TiSpH** [comment]
第一张截图是运行 SRC 时出现的，第二张正常的截图是之后手动在 python 里执行了
```
updater = module.webui.updater.Updater()
updater.update()
```
之后产生的

**Comment by TiSpH** [comment]
Debug 了一下发现是启动开始检查更新的时候 `webui.config.DeployConfig.read` 将 `Repository` 又给读成了 `global`。
```
====== Watchpoints Triggered ======
Call Stack (most recent call last):
  default_lifespan (/opt/miniconda3/envs/src/lib/python3.10/site-packages/starlette/routing.py:481):
>   await self.startup()
  startup (/opt/miniconda3/envs/src/lib/python3.10/site-packages/starlette/routing.py:518):
>   handler()
  startup (/Users/tisph/Documents/test/StarRailCopilot/module/webui/app.py:1254):
>   if updater.delay > 0:
  delay (/Users/tisph/Documents/test/StarRailCopilot/module/webui/updater.py:29):
>   self.read()
  read (/Users/tisph/Documents/test/StarRailCopilot/module/webui/config.py:38):
>   super().__setattr__(key, value)
updater.Repository:
https://github.com/LmeSzinc/StarRailCopilot
->
global
```

解决方法之一是重写 `deploy.Windows.config.ConfigModel.__setattr__`。这里提供一个例子：
[StarRailCopilot/deploy/Windows/config.py.txt](https://github.com/LmeSzinc/StarRailCopilot/files/15061480/config.py.txt) （此修改未在 Windows 版中测试过）

但是更新依旧失败，原因是在这之后 SRC 开始调用了 `StarRailCopilot/toolkit` 里的东西，而手动安装的版本似乎没有这个文件夹。并在 macOS 上试图运行 `python.exe`。

<img width="870" alt="Screenshot 2024-04-22 at 3 35 51 AM" src="https://github.com/LmeSzinc/StarRailCopilot/assets/14122965/32f6f0b7-c219-467c-be57-17715fbe7faf">

相关的日志：[2024-04-22_gui.txt](https://github.com/LmeSzinc/StarRailCopilot/files/15061609/2024-04-22_gui.txt)

目前看起来 SRC 并未完全支持手动安装，调用的似乎都是 Windows 上的部署方案？

**Comment by LmeSzinc** [comment]
#431

**Comment by TiSpH** [comment]
感谢！问题解决了！
