### ISSUE TITLE
模拟器打开星铁到登录界面加载太慢，报错Wait too long

### ISSUE THREAD

**Issue by sola97** [LmeSzinc/StarRailCopilot#47]
使用的是mumu12模拟器，开启了HyperV，到登录界面耗时超过2分钟，如何延长等待时间

**Comment by LmeSzinc** [comment]
关闭 hyperv 打开 VT，模拟器安装在固态硬盘，模拟器实例设置 4 核心 4 GB 内存或以上

**Comment by sola97** [comment]
可能是笔记本的9750H+1660ti跑不动，换台式机10600K+2080ti加载就快很多（两台都要用WSL，开启VT没关闭HyperV的情况下）

**Comment by LmeSzinc** [comment]
模拟器不开 VT 只能分配 1 核心，你应该使用蓝叠 hyperv 版

**Comment by Ding-Kyoma** [comment]
我打开慢的原因是网络延迟太高了……美国玩国服启动都是1-2分钟左右（不是电脑配置问题，ssd+分配4核心及4G内存+4090，可以跑到60fps）。现在只能更改module/device/device.py 中stuck_timer 60改为120临时解决一下 :)

**Comment by LmeSzinc** [comment]
@Ding-Kyoma 有回国的加速器，一般也不要钱，挂在模拟器后台就行
