### ISSUE TITLE
脚本未来会加入对桌面端的支持吗？

### ISSUE THREAD

**Issue by LoSiTeE** [LmeSzinc/StarRailCopilot#52]
我的安卓模拟器都是跑在proxmox的win虚拟机里的，因为套娃的缘故，模拟器在win虚拟机里性能有点渣……碧蓝航线跑起来倒是轻松，星铁完全跑不动。

如果不套娃运行模拟器的话，在win虚拟机中直接运行桌面客户端性能就完全够用了，所以我来问问脚本未来有没有对桌面端进行支持的计划。

**Comment by cjwmiku** [comment]
以下来自lme原话:
差距太大碰磁不了
一是用户体验层面，启动模拟器-启动游戏-执行任务-无任务关闭游戏，这都是自动的，用户只需要点开始，可以完全收到后台，桌面端还要一堆手动的准备任务才能开始
二是代码质量，研究透windows要有很深功力的，还包括win7 win10的不同版本 win11不同版本，它们的接口还有区别，我是搞不定，现在的这些就是网上搜的win32屎拼起来，达不到项目标准。相比之下模拟器连接alas和maa一起研究了两三年是比较成熟了
所以应该不会适配桌面的
