### ISSUE TITLE
添加差分宇宙刷内圈遗器的功能

### ISSUE THREAD

**Issue by snowly233** [LmeSzinc/StarRailCopilot#536]
### 解决方案

1、适配差分宇宙ui，祝福选择器可以暂时先随便选
2、将每周14000分的模拟宇宙修改为打一次周常差分宇宙，并在结尾进行存档
3、往后一周内使用该存档，根据设定好的预设队伍刷内圈遗器（存档的时效性刚好截止至每周一04:00）

**Comment by snowly233** [comment]
然后就可以将模拟宇宙那边的刷遗器舍弃掉，在每日副本处添加内圈遗器本的列表

**Comment by gongfuture** [comment]
但是看了下差分宇宙为了防止自动刷甚至把小地图删掉了，自动寻路是个麻烦事了

**Comment by aaahai00** [comment]
> 但是看了下差分宇宙为了防止自动刷甚至把小地图删掉了，自动寻路是个麻烦事了

最麻烦的事是怎么打一次完整图，后面重复刷都简单，主要是存档不永久

**Comment by Nobodylikesme1** [comment]
有差分宇宙之后，进模拟宇宙会自动跳到差分宇宙，有什么解决办法嘛？

**Comment by aaahai00** [comment]
> 有差分宇宙之后，进模拟宇宙会自动跳到差分宇宙，有什么解决办法嘛？

这个明显是个bug，等后面适配吧

**Comment by woqucao** [comment]
我觉得先把重复刷解决好，刷存档后面再说，因为刷存档还需要考虑配比，重复刷就相对更需要一些

**Comment by snowly233** [comment]
> > 但是看了下差分宇宙为了防止自动刷甚至把小地图删掉了，自动寻路是个麻烦事了
> 
> 最麻烦的事是怎么打一次完整图，后面重复刷都简单，主要是存档不永久

我看差分宇宙没有岔路，都是一路直行，或许可以直接使用3d识别可破坏物品、怪物跟门

**Comment by aaahai00** [comment]
> > > 但是看了下差分宇宙为了防止自动刷甚至把小地图删掉了，自动寻路是个麻烦事了
> > 
> > 最麻烦的事是怎么打一次完整图，后面重复刷都简单，主要是存档不永久
> 
> 我看差分宇宙没有岔路，都是一路直行，或许可以直接使用3d识别可破坏物品、怪物跟门

原则上没什么问题，现在最麻烦的是识别不够精确，老的模拟经常都找不到门，新的估计更地狱，要改的地方一大堆，但确实有可行性
不过不知道是不是固定距离，是的话就好弄

**Comment by LmeSzinc** [comment]
#560

**Comment by Looongting** [comment]
要是能进去打第一关就退也好（主要是想刷等级
