### ISSUE TITLE
希望提供养成规划用户自主填写刷取物品及数量的功能

### ISSUE THREAD

**Issue by gongfuture** [LmeSzinc/StarRailCopilot#537]
### 你的功能请求是否与问题有关？

 #514  #520 主要是我个人的使用感受和这两个issue有关，现有的官方自动计算器有诸多不便，例如每次仅能计算一个人或光锥，多个计划累加会出现重复计算背包的问题

### 解决方案

我使用的是相对麻烦一点的[seelie.me](https://hsr.seelie.me/planner)对背包内容和养成计划进行管理。除去目前还需要的手动比对同步背包内容外，seelie对计划养成部分的计算十分便捷，会自动将某一物品需要的总数量计算出来。所以只需添加一个用户自主填写刷取的部分就可以

### 其他内容

另：我在json中也看到了相应的部分，但是没有完全看懂该如何填写。如果能在文档中加入相应说明也可以，感激不尽

**Comment by LmeSzinc** [comment]
不支持添加，养成规划的目的就是抹平游戏系统的复杂性，封装出更便于使用的高层功能。这是从根本需求出发的设计，打副本是手段不是目的，打副本的目的是养成角色和养成仪器，养成规划便是满足了其中的一部分需求 养成角色。需要什么养成材料，每种材料需要什么数量，刷材料需要去哪个副本，这些问题是功能的内部实现问题，不应该暴露出来让用户去操心，使用高层功能不应该关心底层实现，否则就失去了养成规划的最初设计目的。

**Comment by gongfuture** [comment]
了解
