### ISSUE TITLE
[BUG]一直显示[Device Orientation] 1 (HOME key on the right)

### ISSUE THREAD

**Issue by jasonuly** [LmeSzinc/StarRailCopilot#55]
今天下午配置好后正常运行，但晚上就开始报错，无法登录进游戏正常工作，求解答。（mumu12，huaweiP50P模拟环境）

**Comment by cjwmiku** [comment]
如何上报 BUG
在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。
上报问题需要提供出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图，用压缩包打包上传到群文件。若不是错误而是非预期的行为，可以在 log 目录下找到当天的 *_alas.log 并提供一些游戏截图。
