### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Law2333** [LmeSzinc/StarRailCopilot#552]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

启动后卡住，错误提示：
fatal: unable to access 'https://github.com/LmeSzinc/StarRailCopilot/': SSL certificate problem: unable to get local issuer certificate
Error: fatal: unable to access 'https://github.com/LmeSzinc/StarRailCopilot/': SSL certificate problem: unable to get local issuer certificate

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
Last command: "D:/program_files/tools/StarRailCopilot/toolkit/Git/mingw64/bin/git.exe" fetch origin master
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe
Take the screenshot of entire window if you need help
fatal: unable to access 'https://github.com/LmeSzinc/StarRailCopilot/': SSL certificate problem: unable to get local issuer certificate
Error: fatal: unable to access 'https://github.com/LmeSzinc/StarRailCopilot/': SSL certificate problem: unable to get local issuer certificate
```

### 截图

![Snipaste_2024-06-28_18-29-19](https://github.com/LmeSzinc/StarRailCopilot/assets/53925625/6726e53a-4b64-4e1c-bada-060a35d89a2d)

**Comment by 343505817** [comment]
所以这个问题怎么解决？
