### ISSUE TITLE
希望能支持通过adb直接连接物理手机而非模拟器

### ISSUE THREAD

**Issue by ghg6666678** [LmeSzinc/StarRailCopilot#553]
### 你的功能请求是否与问题有关？

电脑配置实在太低，又玩国际服用不了云版本，想连接手机使用adb控制提示分辨率不正确，使用wm size命令修改后依然无效

### 解决方案

希望判定分辨率的形式改变一下，不要直接读取硬件的分辨率

### 其他内容

![image](https://github.com/LmeSzinc/StarRailCopilot/assets/97784469/405a9b62-df48-491f-aa78-baf849c03c9b)

**Comment by ghg6666678** [comment]
当我更改之后无论改成1280*720还是720*1280都会报一样的错误
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/97784469/c15ae1ff-62ec-4130-a3b5-108ff37b78e7)

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Emulator_cn#-%E5%9C%A8%E5%AE%89%E5%8D%93%E7%9C%9F%E6%9C%BA%E8%BF%90%E8%A1%8C%E6%B8%B8%E6%88%8F%E7%94%B5%E8%84%91%E8%BF%90%E8%A1%8Calas

**Comment by aaahai00** [comment]
支持真机运行的，你只需要手机手动开放一下adb（这里建议无线调试），填写IP跟端口号就可以用了，记得把你的真机的分辨率提前设置为1280x720，这样就可以愉快的跑起来了
长期使用的话建议写个脚本方便运行
并且真机是不能熄屏的，你可以root后借助模块直接关闭显示屏，这样不受影响
至于普通的adb权限好像是可以做到关闭显示器的，但能不能用我就不知道了
并且部分机型分辨率调不了，这种就只能说放弃了（比如我的mix4就改不到1280x720）
