### ISSUE TITLE
无法使用角色养成规划

### ISSUE THREAD

**Issue by xuruixiang2008** [LmeSzinc/StarRailCopilot#557]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

根据wiki教程按步骤操作，但并未识别出页面

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

这是log
[1719725737855.zip](https://github.com/user-attachments/files/16043310/1719725737855.zip)

**Comment by X-Zero-L** [comment]
把设备dpi设置为240

**Comment by xuruixiang2008** [comment]
> 把设备dpi设置为240

可以用了，谢谢！
