### ISSUE TITLE
在SRC设置中添加 关闭游戏声音 选项

### ISSUE THREAD

**Issue by jbhbububuv** [LmeSzinc/StarRailCopilot#584]
### 你的功能请求是否与问题有关？

在游玩其他游戏时被崩铁声音吵到
每次需要手动打开音量合成器关闭模拟器声音

### 解决方案

在SRC设置中添加 关闭游戏声音 选项

**Comment by LmeSzinc** [comment]
模拟器自带禁用声音的功能，这是一次设置永久有效的，如果希望有声音就自己重新打开。
这属于偏好设置，不需要脚本代劳。
