### ISSUE TITLE
加入显示云崩铁剩余时间

### ISSUE THREAD

**Issue by jbhbububuv** [LmeSzinc/StarRailCopilot#588]
### 你的功能请求是否与问题有关？

希望在日志上方的8个信息外加入云崩铁剩余时间

**Comment by LmeSzinc** [comment]
这里可以看，但不会进入仪表盘，理由同 https://github.com/LmeSzinc/StarRailCopilot/issues/160#issuecomment-1762860125
![image](https://github.com/user-attachments/assets/d986df76-bdca-49db-aa84-faf1ec56b7fe)
