### ISSUE TITLE
由于目标计算机积极拒绝，无法连接

### ISSUE THREAD

**Issue by oldman3344** [LmeSzinc/StarRailCopilot#593]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

download error from                                      
         mirror(HTTPSConnectionPool(host='tool.appetizer.io', port=443): Max     
         retries exceeded with url:                                              
         /openatx/atx-agent/releases/download/0.10.0/atx-agent_0.10.0_linux_386.t
         ar.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection
         object at 0x0000022252C723B0>: Failed to establish a new connection:    
         [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))), use origin     
         source
         
         FileNotFoundError: [Errno 2] No such file or directory:  
         'D:\\Program Files (x86)\\Tencent\\message\\WeChat\\WeChat              
         Files\\wxid_8949uygixevc32\\FileStorage\\File\\2024-07\\StarRailCopilot_
         0.5.5_fullcn\\StarRailCopilot\\toolkit\\lib\\site-packages\\uiautomator2
         cache\\cache\\atx-agent_0.10.0_linux_386.tar.gz-1f8cdf3239\\atx-agent_0.
         10.0_linux_386.tar.gz.part'  

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
贴出完整 log

**Comment by AAAtaixueggpifa** [comment]
检查游戏内用于角色养成的材料的副本是否全部解锁
