### ISSUE TITLE
Error occurred upon startup

### ISSUE THREAD

**Issue by dark-knifes** [LmeSzinc/StarRailCopilot#60]
刚启动SRC就报错力
游戏停留在正常界面
![2023-08-14_16-50-48-468208](https://github.com/LmeSzinc/StarRailCopilot/assets/75507531/78938f76-7d84-4e1e-b55f-7abbf3576cc4)
但启动SRC光速报错
日志：
[1692003050716.zip](https://github.com/LmeSzinc/StarRailCopilot/files/12333160/1692003050716.zip)

**Comment by dark-knifes** [comment]
按照教程重装一遍还是会报错，看了一下是pip装依赖的时候出错了,是不是版本需求写错了
``Collecting numpy==1.24.3 (from -r .\StarRailCopilot\requirements.txt (line 39))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f0/e8/1ea9adebdccaadfc208c7517e09f5145ed5a73069779ff436393085d47a2/numpy-1.24.3-cp311-cp311-win_amd64.whl (14.8 MB)
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.14.1 (from versions: 1.15.0, 1.15.1)
ERROR: No matching distribution found for onnxruntime==1.14.1``

**Comment by dark-knifes** [comment]
删了之前装的python就不会报错了()

**Comment by dark-knifes** [comment]
建议安装教程里面加一个提示报错可以考虑删除原有python环境

**Comment by LmeSzinc** [comment]
安装教程已经写了需要新建python3.10虚拟环境，但是你依然坚持使用python3.11

![image](https://github.com/LmeSzinc/StarRailCopilot/assets/37934724/be10b21c-ee0f-49a2-9fda-57cdbb1e605b)

**Comment by dark-knifes** [comment]
> 安装教程已经写了需要新建python3.10虚拟环境，但是你依然坚持使用python3.11
> 
> ![image](https://user-images.githubusercontent.com/37934724/260736747-be10b21c-ee0f-49a2-9fda-57cdbb1e605b.png)

311是我原有的python版本，SRC我是用conda创建310环境的

**Comment by wizardt** [comment]
我跟你一样，windows里已经安装3106，anaconda默认311版本，虚拟环境创建31010， 但他还是自动去下载311的依赖，所以我觉得是anaconda的问题

> > 安装教程已经写了需要新建python3.10虚拟环境，但是你依然坚持使用python3.11
> > ![image](https://user-images.githubusercontent.com/37934724/260736747-be10b21c-ee0f-49a2-9fda-57cdbb1e605b.png)
> 
> 311是我原有的python版本，SRC我是按照教程用conda创建了310环境，再下载依赖的

**Comment by wizardt** [comment]
命令行直接建venv好像就是不行，试试去图形界面把31010的切换为正在使用的环境，然后再试一次 pip
