### ISSUE TITLE
Provide an option to change the waiting time during startup.

### ISSUE THREAD

**Issue by dark-knifes** [LmeSzinc/StarRailCopilot#61]
提供一个更改启动时间过长自动重启时等待时长的选项
如果把模拟器的配置拉低到不影响日常使用或者电脑配置较低时，启动hksr所需时长就比较长，导致SRC不断重启游戏直到报错。
我看到[#56](https://github.com/LmeSzinc/StarRailCopilot/issues/56)也有人提到这个需求，但又自己关闭了，就再提出一遍

**Comment by BeatSeat** [comment]
实际上还有一种情况，就是游戏在更新下载资源。假如不等久一点下载不完的
