### ISSUE TITLE
日常任务不工作，任务可以识别成功，但“No more quests able to do   ”直接待机了。

### ISSUE THREAD

**Issue by wizardt** [LmeSzinc/StarRailCopilot#62]
请问大佬，任务可以识别成功，但“No more quests able to do   ”。直接待机了。，是怎么回事呢
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/9411014/74b9c9a5-e461-4073-92e7-eb04ce02349f)
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/9411014/4b825c80-0d73-4bf2-82da-5a4103aa74ce)

**Comment by LmeSzinc** [comment]
每日任务还没完全支持，近期会增加任务之间的联动，来完成要求打xx本这样的每日

**Comment by Small-Ku** [comment]
9aaadc4136dc40b17de1c61e730b51e402cff125 應該解決了吧
![圖片](https://github.com/LmeSzinc/StarRailCopilot/assets/16464896/31c14896-63de-489e-8523-6c7eaef6eded)
凝滯虛影/侵蝕隧洞則是要先設定好

**Comment by wizardt** [comment]
> 

也是通过识别图片+传送+录制脚本 实现吧

**Comment by wizardt** [comment]
> 每日任务还没完全支持，近期会增加任务之间的联动，来完成要求打xx本这样的每日

收到 ٩( 'ω' )و get！

**Comment by LmeSzinc** [comment]
大部分每日已经适配完成了，现在每天基本都能拿满500点

![image](https://github.com/LmeSzinc/StarRailCopilot/assets/37934724/e0ca5ab1-f980-4def-8ad9-d6d1093fd6ca)
![image](https://github.com/LmeSzinc/StarRailCopilot/assets/37934724/30ae0b9e-2547-4cc1-bc1f-eaa3f07825ef)
