### ISSUE TITLE
无法正确刷取遗器副本

### ISSUE THREAD

**Issue by github123520** [LmeSzinc/StarRailCopilot#624]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

开发者你好，副本选择遗器均无法正常找到对象并刷图，怀疑是早上更新之后变动了位置，冰套和超击破套都是

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by mliucc** [comment]
不只是遗器副本，很大一部分的角色晋阶材料也不行，看日志貌似是识别文字时出现错别字导致不能识别吧

**Comment by a90091343** [comment]
滚动识别刷哪个本好像是有内置的顺序表的吧，现在更新后好多本的顺序全变了，程序自然就卡住不动了

**Comment by LmeSzinc** [comment]
#626
