### ISSUE TITLE
建议将每日人物设置为每次启动都检查或一天检查两次

### ISSUE THREAD

**Issue by pavocritatus** [LmeSzinc/StarRailCopilot#645]
### 你的功能请求是否与问题有关？

每日任务当前每天默认设置只运行一次，若早晨使用时体力不足以完成全部每日，就会因为下一次启动每日任务的时间在第二天而不能自动拿走星琼

### 解决方案

将每日任务的每天启动次数改为不止一次，比如在每天第一次使用后数个小时再运行一次，或者干脆设置为每次启动都检查

**Comment by LmeSzinc** [comment]
每日任务会在需要运行的时候被唤起，SRC 不是简单把每个任务顺序运行一次的按键精灵
