### ISSUE TITLE
网页无法显示日志

### ISSUE THREAD

**Issue by TiSpH** [LmeSzinc/StarRailCopilot#669]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

在 Mac 上运行的 SRC，UI 用 Safari 显示。最近从 M2 Mac mini 迁移到 M4 Mac mini 出现了此问题。无论是重新 git clone 还是从旧 Mac 上复制都无法解决

### 如何复现

1. git clone https://github.com/LmeSzinc/StarRailCopilot
2. cd StarRailCopilot
3. conda create -n src python==3.10.10
4. conda activate src
5. pip install -r requirements-in.txt
6. python gui.py
7. 打开 Safari 前往 http://localhost:22367
8. 点击启动
9. 没有显示任何日志

### 预期行为

日志框显示终端中的部分日志

### 相关 Logs

[2024-11-09_gui.txt](https://github.com/user-attachments/files/17689864/2024-11-09_gui.txt)
[2024-11-09_src.txt](https://github.com/user-attachments/files/17689865/2024-11-09_src.txt)

后续补增终端输出日志，时间与其他日志和截图不一致，但问题一致
[终端输出.txt](https://github.com/user-attachments/files/17690682/default.txt)

### 截图

<img width="1334" alt="Screenshot 2024-11-09 at 5 26 44 PM" src="https://github.com/user-attachments/assets/a5ad64ed-2d62-4b52-bbf1-1cae1eae68ac">
<img width="1334" alt="Screenshot 2024-11-09 at 5 49 04 PM" src="https://github.com/user-attachments/assets/83246c8d-ea5f-4f4f-b18b-bbaf9bfd2280">

### 还有别的吗？

M4 Mac mini
macOS 15.1 (24B2083)
Safari 18.1 (20619.2.8.11.10)
SRC 7442fc98a
截止 2024年11月10日，上述软件均为最新版本

**Comment by Caspppp** [comment]
我也遇到了同样的问题设备也是M4Macmini
<img width="1154" alt="截屏2024-11-10 06 35 15" src="https://github.com/user-attachments/assets/3824a106-4e69-40e4-bc37-67cc32396b57">
，能顺便问问大佬用的什么模拟器吗，刚开始捣鼓Mac想挂俩号，但是在mumupro上目前我只成功让一个号挂着

**Comment by TiSpH** [comment]
我也用的 mumu pro，两个号的话没试过，可以试试：
1. mumu pro 里复制崩铁的模拟器，启动并记下 adb 端口号，应该和第一个是不一样的，记为 adp_port_2
2. 复制 SRC 文件夹，记为 SRC_2
3. 在 SRC_2/config/deploy.yaml 里找到 WebuiPort 改为任意一个没被占用的端口，记为 webui_port_2
4. 在 SRC_2/config/src.json 里找到 Serial 把`:`后面的端口号改成 adp_port_2
5. 在 SRC_2 中照常启动，浏览器打开 http://localhost:webui_port_2

**Comment by TiSpH** [comment]
在 Windows 上用 Edge 130.0.2849.80 (Official build) (64-bit) 访问了 macOS 上的 SRC 依旧有此问题，或许可以排除浏览器的问题？
![SRC and 1 more page - Personal - Microsoft​ Edge 11_9_2024 11_51_15 PM](https://github.com/user-attachments/assets/bbeb0026-e509-4554-bcf5-507c085cac6d)

**Comment by Caspppp** [comment]
感谢大佬提供建议，我之后研究一下你说的方法，还有我用的是chrome浏览器（具体版本我不清楚），上面的截图就是在这截的，感觉应该不会是浏览器的问题

**Comment by TiSpH** [comment]
debug 了一下发现是新版的 rich 改了 Console 导致 module.webui.widgets.RichLog.render 返回的 html 为空。把 rich 退回到 requirements.txt 里的版本就行了。已提交修改，更新后重新 pip install -r requirements-in.txt 就行了。

**Comment by Caspppp** [comment]
大佬牛的，更新后一下就正常了。而且我发现开两个号的话，直接复制config文件夹下的src.json文件就好了，可以在网页控制俩，就不需要再复制一个SRC 文件夹了
<img width="179" alt="image" src="https://github.com/user-attachments/assets/4b54727a-3fcb-43d0-923b-626b9d0427c8">
