### ISSUE TITLE
每次登录后进入游戏，scrcpy server必死

### ISSUE THREAD

**Issue by iblueer** [LmeSzinc/StarRailCopilot#670]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

请直接看日志。我通过src启动任务，模拟器自动打开了游戏，然后进入了游戏世界。然后scrcpy server就直接stop了。无法进行后续的任何动作。

每次都是这样。

模拟器：mumu12
系统：win11专业版

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

![PixPin_2024-11-10_10-11-47](https://github.com/user-attachments/assets/f39f373a-1416-4151-aaf3-b25eade42ea9)

**Comment by LmeSzinc** [comment]
调度器没有任务需要运行，scrcpy server 停止是释放资源
