### ISSUE TITLE
模拟宇宙领取遗器问题

### ISSUE THREAD

**Issue by aaahai00** [LmeSzinc/StarRailCopilot#671]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

不确定该问题是否是bug
在启用了饰品提取功能（但差分宇宙没有存档，使用开拓力刷选项也开了）后模拟宇宙关于遗器的功能失效，表现为刷每周积分不提取仪器直接跳到下一层，有双倍内圈活动也不会自己刷，也不会跳过每日副本直接刷内圈遗器（相关功能已开启）

### 预期行为

在模拟宇宙刷每周积分根据“沉浸器领取仪器”选项决定打完boss领不领遗器
双倍内圈优先走饰品提取流程，若没有存档，再回到普通模拟宇宙刷
开拓力刷内圈优先饰品提取，没存档走模拟宇宙

### 还有别的吗？

在勾选界面没有提示这两个地方是冲突的导致我反复测试，如果不打算修改的话把至少把提示加上
这两个功能本来理应二选一，但因为差分宇宙的存档只能手动去刷（都用src了大多数时候都不想去刷存档，模拟宇宙刷不到的遗器除外）

**Comment by LmeSzinc** [comment]
用户开启饰品提取功能就意味着 他希望通过饰品提取这个游戏系统刷仪器，在这个情况下去刷模拟宇宙我觉得不妥，并且这两个系统并不是完全等价的，新套装已经不加到老模拟宇宙里了，因此模拟宇宙不能成为饰品提取的回退。
饰品提取现在要求拥有保存存档，但很明显大部分人都不能在每周一凌晨4点抢在 SRC 之前先打一个存档，所以饰品提取任务会自己推迟自己直到用户拥有存档，相当于给了一个缓冲期。如果在没有存档的情况下直接打模拟宇宙，那 SRC 就直接一个偷袭把体力和每周送的沉浸器霍霍到一个 非用户预期 的套装里了，这才是欲哭无泪。
