### ISSUE TITLE
委托报错

### ISSUE THREAD

**Issue by jbhbububuv** [LmeSzinc/StarRailCopilot#676]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

新活动委托界面报错

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![2024-11-15_22-59-00-931429](https://github.com/user-attachments/assets/d81f0bca-cc02-43e0-a786-dd780758d6c0)

### 还有别的吗？

[error.zip](https://github.com/user-attachments/files/17777854/error.zip)

**Comment by LmeSzinc** [comment]
#675
