### ISSUE TITLE
完成每日任务,活跃度500/500, 过几小时后重新启动模拟器,重新启动游戏, 每日任务选项卡没有判断就选择了

### ISSUE THREAD

**Issue by destaus** [LmeSzinc/StarRailCopilot#679]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

完成活跃度后,  又积累了一些体力,再次运行遗器本, 判断选项卡没有进行, 在每日任务界面拖动, 以为是选择遗器本

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
有问题发 log

**Comment by destaus** [comment]
> 有问题发 log

问题找到了, 我用的版本是0.54或者0.52, 把旧版路径改了,安装新版,没这个问题了
要不加个关于,显示一下版本号吧.

**Comment by Xiaoqianghepipi** [comment]
看起来是ocr识别的问题，我这边也有类似的问题

**Comment by destaus** [comment]
新鲜出炉的典型的Log


INFO     01:41:20.369 │ [Lang] cn                                              
INFO     01:41:20.373 │ Bind task ['Alas']                                     
INFO     01:41:20.374 │ Pending tasks: ['Ornament', 'Dungeon']                 
INFO     01:41:20.375 │ [Task] Ornament (Enable, 2024-12-03 18:43:15)          
INFO     01:41:20.376 │ Bind task ['Alas', 'Ornament']                         
INFO     01:41:20.379 │ Scheduler: Start task `Ornament`                       
═══════════════════════════════════════════════════════════════════════════════
                                   ORNAMENT                                    
═══════════════════════════════════════════════════════════════════════════════
INFO     01:41:20.433 │ Bind task ['Alas', 'Ornament']                         
INFO     01:41:20.434 │ [BattlePassWeeklyQuest] {'time':                       
         datetime.datetime(2024, 12, 3, 11, 37, 41), 'quest1':                 
         'Clear_Cavern_of_Corrosion_1_times', 'quest2':                        
         'Synthesize_Consumables_1_times', 'quest3': '', 'quest4': '',         
         'quest5': '', 'quest6': '', 'quest7': '', 'total': 7, 'value': 0}     
INFO     01:41:20.435 │ [BattlePassWeeklyQuest expired] False                  
INFO     01:41:20.436 │ [DailyActivity] {'time': datetime.datetime(2024, 12, 3,
         11, 37, 48), 'total': 500, 'value': 500}                              
INFO     01:41:20.437 │ [DailyActivity expired] False                          
INFO     01:41:20.437 │ [DailyQuest] {'time': datetime.datetime(2024, 12, 3,   
         11, 37, 48), 'quest1': '', 'quest2': '', 'quest3': '', 'quest4': '',  
         'quest5': '', 'quest6': '', 'quest7': '', 'quest8': '', 'total': 8,   
         'value': 8}                                                           
INFO     01:41:20.438 │ [DailyQuest expired] False                             
INFO     01:41:20.440 │ Bind task ['Alas', 'Ornament']                         
INFO     01:41:20.441 │ [DungeonDouble] {'time': datetime.datetime(2024, 12, 3,
         11, 21, 48), 'calyx': 0, 'relic': 0, 'rogue': 0}                      
INFO     01:41:20.442 │ [DungeonDouble expired] False                          
INFO     01:41:20.442 │ [Ornament_UseStamina] True                             
INFO     01:41:20.443 │ [called_daily_support] False                           
INFO     01:41:20.444 │ [DungeonSupport_Use] always_use                        
INFO     01:41:20.445 │ [Require compulsory support] False                     
═════════════════════════════════ DUNGEON RUN ═════════════════════════════════
INFO     01:41:20.446 │ DUNGEON RUN                                            
INFO     01:41:20.446 │ Dungeon: DungeonList(Divergent_Universe_Fruit_of_Evil),
         team=1, wave_limit=0, support_character=FirstCharacter                
INFO     01:41:20.460 │ No dungeon interact                                    
────────────────────────────── DUNGEON TAB GOTO ───────────────────────────────
INFO     01:41:20.461 │ DUNGEON TAB GOTO                                       
INFO     01:41:20.462 │ <<< UI ENSURE >>>                                      
INFO     01:41:20.463 │ UI get current page                                    
INFO     01:41:20.464 │ [UI] page_main                                         
INFO     01:41:20.473 │ acquire_lang_checked                                   
INFO     01:41:20.474 │ <<< UI GOTO PAGE_MAIN >>>                              
INFO     01:41:20.475 │ Page arrive: page_main                                 
INFO     01:41:20.636 │ Page arrive confirm page_main                          
INFO     01:41:20.638 │ check_lang_from_map_plane                              
INFO     01:41:20.638 │ Try ocr in lang cn                                     
INFO     01:41:20.848 │ [OCR_MAP_NAME 0.209s] 晖长石号同白                     
INFO     01:41:20.850 │ [CurrentPlane] MapPlane(Penacony_TheRadiantFeldspar)   
INFO     01:41:20.850 │ check_lang_from_map_plane matched lang: cn             
INFO     01:41:20.851 │ UI get current page                                    
INFO     01:41:20.853 │ [UI] page_main                                         
INFO     01:41:20.853 │ Goto page_guide                                        
INFO     01:41:20.854 │ <<< UI GOTO PAGE_GUIDE >>>                             
INFO     01:41:20.855 │ Page switch: page_main -> page_guide                   
INFO     01:41:20.967 │ Page arrive confirm page_main                          
INFO     01:41:20.968 │ Click (1003,   49) @ MAIN_GOTO_GUIDE                   
INFO     01:41:25.612 │ Page arrive: page_guide                                
INFO     01:41:25.613 │ DungeonTab set to DungeonTab(Survival_Index)           
INFO     01:41:25.654 │ [DungeonTab] unknown                                   
INFO     01:41:25.664 │ Click ( 160,   98) @ SURVIVAL_INDEX_CLICK              
INFO     01:41:25.729 │ [DungeonTab] unknown                                   
INFO     01:41:25.828 │ [DungeonTab] unknown                                   
INFO     01:41:25.930 │ [DungeonTab] unknown                                   
INFO     01:41:26.031 │ [DungeonTab] DungeonTab(Survival_Index)                
INFO     01:41:26.032 │ Tab goto DungeonTab(Survival_Index), wait until loaded 
WARNING  01:41:28.054 │ Wait survival index loaded timeout                     
────────────────────────────── DUNGEON NAV GOTO ───────────────────────────────
INFO     01:41:28.056 │ DUNGEON NAV GOTO                                       
INFO     01:41:28.056 │ Dungeon nav goto DungeonNav(Ornament_Extraction)       
INFO     01:41:28.330 │ [OCR_DUNGEON_NAV 0.272s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:28.331 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:28.332 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:28.623 │ [OCR_DUNGEON_NAV 0.281s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:28.625 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:28.626 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:28.869 │ [OCR_DUNGEON_NAV 0.232s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:28.870 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:28.871 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:29.123 │ [OCR_DUNGEON_NAV 0.242s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:29.125 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:29.126 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:29.387 │ [OCR_DUNGEON_NAV 0.250s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:29.391 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:29.394 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:29.645 │ [OCR_DUNGEON_NAV 0.241s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:29.647 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:29.648 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:29.893 │ [OCR_DUNGEON_NAV 0.236s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:29.895 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:29.895 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:30.144 │ [OCR_DUNGEON_NAV 0.239s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:30.146 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:30.146 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:30.408 │ [OCR_DUNGEON_NAV 0.251s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:30.410 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:30.411 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:30.669 │ [OCR_DUNGEON_NAV 0.246s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:30.672 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:30.672 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:30.924 │ [OCR_DUNGEON_NAV 0.242s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:30.927 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:30.928 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:31.173 │ [OCR_DUNGEON_NAV 0.236s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:31.175 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:31.176 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:31.438 │ [OCR_DUNGEON_NAV 0.249s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:31.441 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:31.442 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:31.714 │ [OCR_DUNGEON_NAV 0.262s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']                                           
INFO     01:41:31.717 │ [OCR_DUNGEON_NAV matched] []                           
WARNING  01:41:31.718 │ No valid rows loaded into DraggableList(DungeonNavList)
INFO     01:41:31.982 │ [OCR_DUNGEON_NAV 0.254s] ['500', '0', '100', '进度 1   
         /1', '进度', '使用支援角色并获', '完', '得战斗胜利1次', '+200',       
         '活跃度', '本日活跃度已满']

**Comment by kafuneri** [comment]
是普遍现象吗？我也是这个问题
```────────────────────────────────── DUNGEON INSIGHT (SORT) ───────────────────────────────────
INFO     15:54:13.070 │ DUNGEON INSIGHT (SORT)                                               
INFO     15:54:13.072 │ Dungeon insight:                                                     
         DungeonList(Calyx_Crimson_Erudition_Jarilo_RivetTown)                               
INFO     15:54:14.062 │ [OcrDungeonList 0.985s] ['200', '300', '500', '进度 0 / 1',          
         '将任意遗器等级提分宇', '升1次', '以宇', '+100', '30', '活跃度', '度',              
         '本日活跃度已满已满']                                                               
INFO     15:54:14.075 │ [OcrDungeonList matched] []                                          
WARNING  15:54:14.079 │ No valid rows loaded into DraggableList(DungeonList)                 
WARNING  15:54:14.082 │ No more rows loaded                                                  
INFO     15:54:14.085 │ Drag ( 691,  576) -> ( 691,  212)                                    
INFO     15:54:14.752 │ dungeon_list_wait_list_end                                           
INFO     15:54:14.811 │ Wait until stable: OCR_DUNGEON_NAME                                  
INFO     15:54:14.992 │ OCR_DUNGEON_NAME stabled                                             
INFO     15:54:16.044 │ [OcrDungeonList 1.043s] ['200', '300', '500', '进度 0 / 1',          
         '将任意遗器等级提分宇', '升1次', '{宇', '+100', '10', '活跃度',                     
         '本日活跃度已满已满']                                                               
INFO     15:54:16.051 │ [OcrDungeonList matched] []                                          
WARNING  15:54:16.054 │ No valid rows loaded into DraggableList(DungeonList)                 
WARNING  15:54:16.057 │ No more rows loaded                                                  
INFO     15:54:16.060 │ Drag ( 685,  574) -> ( 685,  215)                                    
INFO     15:54:16.736 │ dungeon_list_wait_list_end                                           
INFO     15:54:16.811 │ Wait until stable: OCR_DUNGEON_NAME                                  
INFO     15:54:16.963 │ OCR_DUNGEON_NAME stabled                                             
INFO     15:54:17.907 │ [OcrDungeonList 0.937s] ['200', '300', '500', '进度 0 / 1',          
         '将任意遗器等级提分宇', '升1次', '以宇', '+100', '10', '活跃度',                    
         '本日活跃度已满已满']                                                               
INFO     15:54:17.913 │ [OcrDungeonList matched] []                                          
WARNING  15:54:17.916 │ No valid rows loaded into DraggableList(DungeonList)                 
WARNING  15:54:17.919 │ No more rows loaded                                                  
ERROR    15:54:17.921 │ Dungeon list reached end but target dungeon not found                
INFO     15:54:17.923 │ Dungeon list reset                                                   
WARNING  15:54:17.951 │ Unknown dungeon LIST_SORTING                                         
INFO     15:54:19.049 │ [OcrDungeonList 1.094s] ['200', '300', '500', '进度 0 / 1',          
         '将任意遗器等级提分宇', '升1次', '以宇', '+100', '10', '活跃度',                    
         '本日活跃度已满已满']                                                               
INFO     15:54:19.055 │ [OcrDungeonList matched] []                                          
WARNING  15:54:19.061 │ No valid rows loaded into DraggableList(DungeonList)                 
WARNING  15:54:19.065 │ No more rows loaded                                                  
INFO     15:54:19.069 │ Drag ( 655,  570) -> ( 655,  266)                                    
[src] exited. Reason: Manual stop

```
