### ISSUE TITLE
使用角色养成规划会卡在材料合成界面

### ISSUE THREAD

**Issue by PikipikiTime** [LmeSzinc/StarRailCopilot#682]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 SRC

### 描述你的问题

新号，我按步骤扫描角色材料后在执行角色养成规划这里就给我打开材料合成界面，然后啥也不动，就异常重启了，重启好几次都是卡材料合成界面

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/user-attachments/assets/c25075fe-f077-47ec-a9f9-dfb6c7ec6bc6)
![image](https://github.com/user-attachments/assets/315563d1-adbe-48de-a4b2-3c4a5d6e4853)
![image](https://github.com/user-attachments/assets/d36bf25c-6d5c-4129-afd5-305cf1f78758)
![image](https://github.com/user-attachments/assets/a2204405-67e0-497e-bcbf-99ade5212453)
![image](https://github.com/user-attachments/assets/8c59f02c-2a8a-40a0-858c-039418352dbd)
![image](https://github.com/user-attachments/assets/975bf243-8cb9-4efd-9ff7-ecee6076777a)
![image](https://github.com/user-attachments/assets/b8d76637-f5dd-470c-bc7e-85e269fc4637)
![image](https://github.com/user-attachments/assets/525bda64-dd7d-4107-b495-ec271ed53e84)
![image](https://github.com/user-attachments/assets/7f39d848-7f94-417b-a3f8-0e74bb07a6a4)

### 还有别的吗？

MUMU12模拟器

**Comment by LmeSzinc** [comment]
使用养成规划需要解锁紫色材料

**Comment by PikipikiTime** [comment]
> 使用养成规划需要解锁紫色材料

那没事了，我这是新买的自抽号，还没突破
