### ISSUE TITLE
在“当任务队列清空后”添加更加可拓展性的功能

### ISSUE THREAD

**Issue by hhhzy-Sf** [LmeSzinc/StarRailCopilot#694]
### 你的功能请求是否与问题有关？

再完成每日运行后，需要在其他游戏收菜，希望可以在“当任务队列清空后”添加更加可拓展性的功能

### 解决方案

可以在“当任务队列清空后”中的选项中加入一个运行xxx文件，或者是运行xxx批处理命令吗

**Comment by LmeSzinc** [comment]
不支持，这会导致远程执行漏洞，接受以字符串形式输入的命令然后执行是非常危险的
