### ISSUE TITLE
請問這是屬於安裝失敗了嗎

### ISSUE THREAD

**Issue by Arrest3579** [LmeSzinc/StarRailCopilot#7]
Successfully uninstalled anyio-3.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
conda-repo-cli 1.0.41 requires requests_mock, which is not installed.
xarray 2022.11.0 requires packaging>=21.0, but you have packaging 20.9 which is incompatible.
statsmodels 0.13.5 requires packaging>=21.3, but you have packaging 20.9 which is incompatible.
pytoolconfig 1.2.5 requires packaging>=22.0, but you have packaging 20.9 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.
jupyterlab-server 2.19.0 requires packaging>=21.3, but you have packaging 20.9 which is incompatible.
distributed 2022.7.0 requires tornado<6.2,>=6.0.3, but you have tornado 6.3.1 which is incompatible.
conda-repo-cli 1.0.41 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.41 requires nbformat==5.4.0, but you have nbformat 5.7.0 which is incompatible.
conda-repo-cli 1.0.41 requires requests==2.28.1, but you have requests 2.30.0 which is incompatible.
Successfully installed adbutils-1.2.9 aiofiles-23.1.0 anyio-3.6.2 apkutils2-1.0.0 asgiref-3.6.0 av-10.0.0 cached-property-1.5.2 charset-normalizer-3.1.0 cigam-0.0.3 click-8.1.3 coloredlogs-15.0.1 deprecated-1.2.13 deprecation-2.1.0 filelock-3.12.0 flatbuffers-23.5.9 h11-0.14.0 httptools-0.5.0 humanfriendly-10.0 imageio-2.28.1 jellyfish-0.11.2 logzero-1.7.0 lxml-4.9.2 lz4-4.3.2 markdown-it-py-2.2.0 mdurl-0.1.2 mpmath-1.3.0 numpy-1.24.3 onnxruntime-1.14.1 opencv-python-4.7.0.72 packaging-20.9 pillow-9.5.0 ppocr-onnx-0.0.3.9 prettytable-2.2.1 progress-1.6 protobuf-4.23.0 psutil-5.9.3 pyclipper-1.3.0.post4 pydantic-1.10.7 pyelftools-0.29 pygments-2.15.1 pyreadline3-3.4.1 python-dotenv-1.0.0 pywebio-1.6.2 requests-2.30.0 retry-0.9.2 rich-13.3.5 scipy-1.10.1 shapely-2.0.1 sniffio-1.3.0 starlette-0.14.2 sympy-1.12 tornado-6.3.1 tqdm-4.65.0 typing-extensions-4.5.0 ua-parser-0.16.1 uiautomator2-2.16.17 uiautomator2cache-0.3.0.1 urllib3-2.0.2 user-agents-2.2.0 uvicorn-0.17.6 watchgod-0.8.2 wcwidth-0.2.6 websockets-11.0.3 whichcraft-0.6.1 wrapt-1.15.0 xmltodict-0.13.0

**Comment by LmeSzinc** [comment]
现在有自动安装包了，建议使用：https://github.com/LmeSzinc/StarRailCopilot/releases
