### ISSUE TITLE
运行到每日委托的时候提示超时

### ISSUE THREAD

**Issue by Al1fer0us** [LmeSzinc/StarRailCopilot#75]
> INFO     20:27:37.714 │ Assignment report appears                      
INFO     20:27:37.727 │ [OCR_ASSIGNMENT_REPORT_TIME 0.008s] 0:00:00    
INFO     20:27:37.749 │ Click ( 378,  614) @ CLOSE_REPORT              
WARNING  20:28:37.811 │ Wait too long                                  
WARNING  20:28:37.814 │ Waiting for {'EMPTY_SLOT', 'CLOSE_REPORT'}     
INFO     20:28:37.864 │ [Package_name] com.miHoYo.hkrpg                
ERROR    20:28:37.868 │ GameStuckError: Wait too long                  

![image](https://github.com/LmeSzinc/StarRailCopilot/assets/101399556/24ab75de-29fb-4370-85a3-75c7d5a7fe3d)

**Comment by LmeSzinc** [comment]
@Zebartin
```
吕明珠LmeSzinc在轻轨  21:08:33
@Zebartin 卡在 _exit_report() 里了

吕明珠LmeSzinc在轻轨  21:09:10
我的猜测是现在的交互逻辑变化了，收了一个委托之后会自动选择到下一个能收的委托上面
```
