### ISSUE TITLE
在“点击进入”界面有时候会超时

### ISSUE THREAD

**Issue by Al1fer0us** [LmeSzinc/StarRailCopilot#79]
因为在设置了任务队列清空后关闭游戏，所以到下一次执行时就需要重新启动游戏。我发现脚本的各个版本中由它自动启动游戏的话无论是否正常进入到"点击进入"的界面都大概率会提示超时然后卡住（也可能是模拟器的问题，偶尔会卡黑屏或者闪退），不知道有没有什么比较好的解决办法

> WARNING  04:01:05.435 │ Wait too long                                  
WARNING  04:01:05.440 │ Waiting for {'MONTHLY_CARD_GET_ITEM',          
         'BATTLE_PASS_NOTIFICATION', 'USER_AGREEMENT_ACCEPT',          
         'COMBAT_PREPARE', 'MONTHLY_CARD_REWARD', 'COMBAT_EXIT',       
         'MAIN_GOTO_CHARACTER', 'LOGIN_CONFIRM', 'GET_REWARD'}         
INFO     04:01:06.138 │ [Package_name] com.miHoYo.hkrpg                
ERROR    04:01:06.145 │ GameStuckError: Wait too long                  

![image](https://github.com/LmeSzinc/StarRailCopilot/assets/101399556/3cc02904-dc34-4b62-831b-14dc0fb94857)

**Comment by Small-Ku** [comment]
#61
