### ISSUE TITLE
安装依赖的时候卡住了，求求大佬康康

### ISSUE THREAD

**Issue by cly614** [LmeSzinc/StarRailCopilot#81]
小白安装依赖的时候报错这个
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.14.1 (from versions: 1.15.0, 1.15.1)
ERROR: No matching distribution found for onnxruntime==1.14.1
是我哪里出问题了吗，求求大佬帮帮，谢谢

**Comment by LmeSzinc** [comment]
现在有自动安装包了，建议使用：https://github.com/LmeSzinc/StarRailCopilot/releases
