### ISSUE TITLE
每日副本能否增加借助战打10次的选项？

### ISSUE THREAD

**Issue by weiby3** [LmeSzinc/StarRailCopilot#87]
小号只加了大号一个好友，想利用小号借大号助战打10次来给大号2W信用点。
如果是打完了点击再次挑战的话，不会增加助战奖励，只有手动退出再重进借助战才能增加助战奖励。

**Comment by LmeSzinc** [comment]
按照一贯的传统，不会添加任何与帐号切换有关的功能

**Comment by weiby3** [comment]
跟账号切换无关，只用选人-借助战-战斗-退出-选人-借助战-战斗-退出这样循环10次就行了。
