### ISSUE TITLE
对于每日任务里的'完成1次「忘却之庭」'建议

### ISSUE THREAD

**Issue by HellSakura** [LmeSzinc/StarRailCopilot#96]
目前这个功能尚未实现，提供一下我的思路

1. 参考'累计施放2次秘技'，前往深渊一施放2次秘技
2. 在默认选择人物中，我个人的选人界面中火主排在最前，物主排第三
<img width="352" alt="image" src="https://github.com/LmeSzinc/StarRailCopilot/assets/43169031/acd2e427-ae7d-4e66-a213-467b135fa748">
<img width="353" alt="image" src="https://github.com/LmeSzinc/StarRailCopilot/assets/43169031/c78a6f42-3a7f-49d7-a451-d544c1e8721a">

3.根据这个视频[BV1Gz4y1s7u9](BV1Gz4y1s7u9)中，人物普攻位移距离大致推算，火主物主约4格
4. 每次进入深渊一时，人物视角都是面朝中心怪物的，经实验，可以一路点按普通攻击按键触发战斗(以物主为例子，大约8次）
<img width="1218" alt="image" src="https://github.com/LmeSzinc/StarRailCopilot/assets/43169031/87dbcd0e-4a05-499e-b46a-83dedaaf0379">

5. 开启自动战斗完成并结算

**Comment by LmeSzinc** [comment]
e6c19268d6e181a34a751a77a7645033a20c781f
